OLD_LICENSE
packages/core/atlaspack/README.md

Add back MIT license

---

Cargo.lock

I missed updating the Cargo lockfile in [the last PR](#40).

Update lockfile to fix release

---

Cargo.lock
crates/atlaspack/Cargo.toml
crates/atlaspack/src/plugins/config_plugins.rs
crates/atlaspack_plugin_transformer_js/Cargo.toml
crates/atlaspack_plugin_transformer_raw/Cargo.toml
crates/atlaspack_plugin_transformer_raw/src/lib.rs
crates/atlaspack_plugin_transformer_raw/src/raw_transformer.rs
packages/core/integration-tests/test/data-url.js
packages/core/integration-tests/test/integration/data-url/text.js
packages/core/integration-tests/test/javascript.js

Provide relevant context and motivation behind the change, if any
* Add `atlaspack_plugin_transformer_raw` crate
* Add tests for raw and inline string transformer
* Use raw transformer when `@atlaspack/transformer-raw` is encountered
* Update some crate descriptions
* Enable relevant tests

[V3] Add raw transformer

---

packages/core/integration-tests/test/fs.js
packages/core/integration-tests/test/javascript.js
packages/core/integration-tests/test/output-formats.js
packages/core/integration-tests/test/packager.js
packages/core/integration-tests/test/reporters.js
packages/core/integration-tests/test/resolver.js
packages/core/integration-tests/test/scope-hoisting.js
packages/core/integration-tests/test/tracing.js
packages/core/integration-tests/test/workers.js
packages/core/integration-tests/test/worklets.js

Some tests have been fixed in v3 but not enabled, so we will start to enable them
Enable passing  tests for v3

[V3] Enable tests for v3

---

packages/transformers/js/core/src/dependency_collector.rs

Fixing broken main from semantic build conflict https://github.com/atlassian-labs/atlaspack/pull/55

Fix test function name

---

packages/core/core/src/applyRuntimes.js

This PR is a follow up to #75 where we resolved some module not found errors in HMR runtime assets but weren't sure to the exact cause. It turns out that runtime assets marked as `isEntry` can cause havoc for the load order of bundles. While the fix in #75 is still our best short term solution, we either need some way to ensure bundle groups are loaded in a specific order or a better way to handle the execution of entry assets. 
For now this PR just adds a bunch of context to the `applyRuntimes` function for context sharing with the next unlucky soul to touch it.

Document apply runtimes function

---

packages/core/fs/src/NodeVCSAwareFS.js

Fix: Flow check

---

packages/utils/node-resolver-rs/benches/node_resolver_bench.rs

Fixed the red squiggles in the node-resolver bench

V3: Fixed harmless errors in node resolver bench

---

Cargo.lock
crates/atlaspack/Cargo.toml
crates/atlaspack/src/plugins.rs
crates/atlaspack/src/plugins/config_plugins.rs
crates/atlaspack/src/plugins/plugin_cache.rs
crates/atlaspack/src/requests/asset_request.rs
crates/atlaspack/src/requests/path_request.rs
crates/atlaspack_plugin_rpc/src/lib.rs
crates/atlaspack_plugin_rpc/src/nodejs/rpc/nodejs_rpc_worker_farm.rs
crates/atlaspack_plugin_rpc/src/testing.rs
packages/core/core/src/atlaspack-v3/worker/worker.js

Once plugin instance to rule them all

V3: Plugin cache

---

Cargo.lock
Cargo.toml
crates/atlaspack_monitoring/Cargo.toml
crates/atlaspack_vcs/Cargo.toml
crates/node-bindings/Cargo.toml

https://github.com/atlassian-labs/atlaspack/commit/b0a37f61974daa47fed17c18e05048eb7884da1c broke releases due to a configuration error
Move `default-features` to the root Cargo.toml file

Fix default-features on cargo workspace

---

packages/core/core/src/atlaspack-v3/worker/compat/plugin-config.js
packages/core/core/src/atlaspack-v3/worker/worker.js

Adding `loadConfig` for JS plugins, sourced from the existing `PublicConfig` in V2

V3: loadConfig for JS Plugins

---

packages/core/core/src/BundleGraph.js
packages/core/integration-tests/test/javascript.js

Bringing in a bug fix and test from parcel upstream found here: https://github.com/parcel-bundler/parcel/pull/9904/files

Fix another case of parcelRequire being added to multi-target libraries

---

packages/core/core/src/atlaspack-v3/AtlaspackV3.js
packages/core/core/src/atlaspack-v3/WorkerPool.js
packages/core/core/src/atlaspack-v3/worker/worker.js
packages/core/core/test/atlaspack-v3/WorkerPool.test.js
packages/core/core/test/atlaspack-v3/worker.js

Don't shutdown worker threads between integration tests / builds.

Make integration tests run faster

---

packages/core/integration-tests/test/javascript.js

These tests now seem to work in v3

turn on tests now passing in v3

---

packages/core/core/src/requests/AssetGraphRequestRust.js

This PR adds dependencies to assets by relating them during the Rust AssetGraph conversion

V3: Assign deps to assets

---

crates/atlaspack/src/requests/target_request.rs
crates/atlaspack_core/Cargo.toml
crates/atlaspack_core/src/types/environment/engines.rs
crates/atlaspack_plugin_transformer_js/src/js_transformer.rs

Add support for loading `.browserslistrc` files from the project root.

[V3] Add support for .browserslistrc files

---

Cargo.lock

Fixing release with outdated cargo.lock

Fix cargo.lock

---

packages/transformers/js/core/src/magic_comments/visitor.rs
packages/transformers/js/core/src/magic_comments/visitor_test.rs

When diffing build outputs I realised some magic comments were being missed with the new native implementation. It turns out that the offset code in the magic comment visitor was causing the regex to miss in some cases. I'm not entirely sure why it was there in the first place, but removing it fixes all my scenarios and also passes the existing tests. 
I have also validated this against an internal build and it actually out performs the old internal magic comment transformer, catching some cases that it missed.

[V3] Fix magic comment extraction

---

flow-typed/npm/rimraf_v5.x.x.js
packages/core/cache/test/LMDBLiteCache.test.js
packages/core/codeframe/test/codeframe.test.js
packages/core/core/src/Dependency.js
packages/core/core/test/Dependency.test.js
packages/core/core/test/requests/AssetGraphRequestRust.test.js
packages/core/integration-tests/test/bundle-text.js
packages/core/integration-tests/test/bundler.js
packages/core/integration-tests/test/compressors.js
packages/core/integration-tests/test/config-merging.js
packages/core/integration-tests/test/data-url.js
packages/core/integration-tests/test/encodedURI.js
packages/core/integration-tests/test/feature-flags.js
packages/core/integration-tests/test/glsl.js
packages/core/integration-tests/test/graphql.js
packages/core/integration-tests/test/json.js
packages/core/integration-tests/test/json5.js
packages/core/integration-tests/test/namer.js
packages/core/integration-tests/test/packager.js
packages/core/integration-tests/test/plugin.js
packages/core/integration-tests/test/pug.js
packages/core/integration-tests/test/sass.js
packages/core/integration-tests/test/svg-react.js
packages/core/workers/test/cpuCount.test.js
packages/core/workers/test/workerfarm.js
packages/transformers/svg/test/parseFuncIRI.test.js

[Continuing from here](https://github.com/atlassian-labs/atlaspack/pull/276)
Breaking this down into smaller PRs because it will be easier to review and also I can't run the tests locally so smaller changes help with narrowing down issues in the tests

Reliability: Flow types for tests (part 2)

---

packages/core/integration-tests/test/rust.js
packages/core/integration-tests/test/schema-jsonld.js
packages/core/integration-tests/test/svg.js
packages/core/integration-tests/test/ts-types.js
packages/core/integration-tests/test/ts-validation.js
packages/core/integration-tests/test/watcher.js
packages/core/integration-tests/test/webmanifest.js
packages/core/integration-tests/test/xml.js
packages/core/utils/test/sourcemap.test.js

Reliability: Flow types for tests

---

flow-typed/node/assert.js
packages/core/integration-tests/test/scope-hoisting.js

Reliability: Flow types for tests (symbol prop)

---

crates/atlaspack/src/requests/target_request.rs
crates/atlaspack/src/requests/target_request/package_json.rs
crates/atlaspack_core/src/types/atlaspack_options.rs
packages/core/integration-tests/test/javascript.js

This PR adds support for passing in a list of targets or a custom target for a specific build.

[V3] Add support for passed in targets

---

crates/atlaspack_contextual_imports/src/lib.rs

Missing doc comment.
Adding a simple doc comment to explain what the ContextualImportsInlineRequireVisitor does

Add doc comment for contextual imports visitor

---

.github/workflows/release.yml

Fixing broken release tags.
Missing a quote and a permission.

Fix perms and missing quote

---

packages/core/fs/index.d.ts
packages/core/fs/src/NodeVCSAwareFS.js
packages/core/fs/src/index.js

Fixing issues identified while trying to run the POC in a product
- added missing types
- added missing re-export
- resolved promise not returning

fix: missing type, exports and promise error

---

packages/core/core/src/public/Bundle.js
packages/core/core/src/public/BundleGroup.js

This allows them to be logged to console.log when debugging.
Test Plan: N/A

Add console.log inspect to Bundle/BundleGroup

---

yarn.lock

Update stale lockfile

---

.changeset/ten-cheetahs-reflect.md
packages/core/cli/src/makeDebugCommand.js

Try to make it easier to add debug commands.
Test Plan: N/A

Refactor makeDebugCommand

---

package.json
yarn.lock

Chore: Update browserslist

---

.changeset/long-emus-dress.md
crates/atlaspack_core/src/types/feature_flags.rs
crates/atlaspack_plugin_transformer_js/Cargo.toml
crates/atlaspack_plugin_transformer_js/src/js_transformer.rs
packages/core/integration-tests/test/conditional-bundling.js

Unblock the rollout of native assetgraph
Updated the native js transformer to include conditional bundling config on the Asset.meta

V3: Adding conditional bundling config Asset.meta

---

.changeset/short-phones-think.md
crates/node-bindings/src/fs_search.rs

Fix finding project root based on .git directory

---

.changeset/fluffy-seahorses-develop.md

Forgot to add it before merging.
Test Plan: N/A

Add changeset for #376

---

.github/workflows/release.yml

Test Plan: N/A
[no-changeset]: Already captured by another changeset

Try to patch smoke test to run correct image

---

docker/multiarch-node/Dockerfile

Test Plan:
N/A
[no-changeset]: Covered by another changeset

Fix docker image platform arch

---

.github/workflows/release.yml

Test Plan:
Will test binaries manually
[no-changeset]: Already covered by a changeset

Disable arm smoke tests

---

package.json

Fixes canary releases calling pre-publish invalidly
[no-changeset]: Release fix

Fix pre-publish in release

---

.github/workflows/release.yml

To support older glibc versions
Migrate the release pipeline to Ubuntu 22
[no-changeset]: Updating pipeline

Migrated the release pipeline to ubuntu 22

---

.changeset/purple-laws-sing.md
.github/workflows/ci.yml
.github/workflows/release.yml
scripts/debug-symbols.mjs

Builds release native add-on on debian bullseye instead of Ubuntu 22.04
https://github.com/atlassian-labs/atlaspack/actions/runs/14826771674/job/41620991987
https://github.com/atlassian-labs/atlaspack/actions/runs/14826833507

Build release binaries on debian bullseye

---

.changeset/metal-pants-appear.md
Cargo.lock
Cargo.toml
crates/atlaspack_monitoring/Cargo.toml
crates/atlaspack_monitoring/src/lib.rs
crates/atlaspack_monitoring/src/sentry_integration.rs
crates/node-bindings/Cargo.toml
crates/node-bindings/src/lib.rs
scripts/build-native.js

Pass `--features canary` to canary builds

Fix canary build features

---

.changeset/four-pugs-tap.md
Cargo.lock
Cargo.toml
crates/atlaspack_monitoring/Cargo.toml
crates/atlaspack_monitoring/examples/sample_usage.rs
crates/atlaspack_monitoring/src/lib.rs
crates/atlaspack_monitoring/src/sentry_integration.rs
crates/atlaspack_monitoring/src/tracer.rs
packages/core/core/test/Environment.test.js

Update with uploading traces to sentry

---

.github/workflows/release.yml

This was missed in https://github.com/atlassian-labs/atlaspack/pull/490
[no-changeset]: Pipeline only change

Don't store rust cache on dev release builds

---

.changeset/config.json

https://github.com/changesets/changesets/blob/main/docs/config-file-options.md#fixed-array-of-arrays-of-package-names
[no-changeset]: Changesets config update

Fix APVM packages to same version

---

.changeset/soft-donkeys-mix.md
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js

Adding unused feature-flag for caching changes.

Add feature-flag for cache rework

---

.changeset/khaki-chicken-hug.md
crates/atlaspack_vcs/src/lib.rs

Read file contents from git CLI instead of libgit

Fix reading file contents on certain checkouts

---

benchmarks/three-js/scripts/build.mjs

Missed a comment in the last PR
[no-changeset]: Benchmarks are not published

Missed a spot in the benchmarks

---

.changeset/fluffy-tigers-sort.md
packages/reporters/cli/src/CLIReporter.js

Log the time it takes to write the cache

---

packages/utils/dev-dep-resolver/src/main.rs

Test Plan:
N/A
[no-changeset]: N/A

Fix warnings in dev-dep-resolver

---

crates/atlaspack/src/requests/asset_graph_request.rs
crates/atlaspack_core/src/plugin/compressor_plugin.rs
crates/atlaspack_core/src/plugin/namer_plugin.rs
crates/atlaspack_core/src/plugin/optimizer_plugin.rs
crates/atlaspack_core/src/plugin/reporter_plugin.rs
crates/atlaspack_core/src/plugin/resolver_plugin.rs
crates/atlaspack_core/src/plugin/runtime_plugin.rs
crates/atlaspack_core/src/plugin/validator_plugin.rs
crates/atlaspack_filesystem/src/in_memory_file_system.rs
crates/atlaspack_monitoring/examples/sample_usage.rs

Test Plan: Open VSCode problems tab
[no-changeset]: N/A

Fix clippy warnings

---

.changeset/blue-dots-leave.md
packages/core/core/src/RequestTracker.js

Write metadata about the cache into it

---

.changeset/cuddly-cheetahs-turn.md
crates/lmdb-js-lite/__test__/index.test.ts
crates/lmdb-js-lite/index.d.ts
crates/lmdb-js-lite/src/lib.rs
crates/lmdb-js-lite/src/writer.rs
crates/node-bindings/src/lmdb.rs
packages/core/cache/src/LMDBLiteCache.js
packages/core/cache/test/LMDBLiteCache.test.js
packages/core/rust/index.js.flow

This will help build cache debugging tools.
Test Plan: cargo test / yarn test:unit

Add way to iterate cache keys

---

crates/lmdb-js-lite/__test__/index.test.ts
packages/core/cache/test/LMDBLiteCache.test.js

Test Plan: yarn test:unit
[no-changeset]: tests

Fix macOS lmdb unit-tests

---

.changeset/dirty-carrots-mix.md
crates/atlaspack_vcs/src/lib.rs

Log verbose errors when failing to read files

---

crates/node-bindings/src/optimizers/inline_requires_optimizer.rs
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js
packages/core/integration-tests/test/inline-requires.js
packages/core/rust/index.js.flow
packages/optimizers/inline-requires/src/InlineRequires.js

Add multi-threading to inline requires optimizer

---

.changeset/mighty-poems-try.md
crates/atlaspack_monitoring/src/tracer.rs

We are logging too much at the moment.
Test Plan: N/A

Fix log file tracing filter

---

.changeset/wet-worms-confess.md
crates/atlaspack_vcs/src/lib.rs
packages/core/integration-tests/test/vcs-cache.js
packages/core/rust/index.js.flow

Allows files to be missing when deleted.

Fix bug cache where deleted files cause snapshot to fail

---

packages/core/graph/test/Graph.test.js

Sample failed build - https://github.com/atlassian-labs/atlaspack/actions/runs/15339422914/job/43162891531?pr=565
[no-changeset]: Test changes
Test Plan: yarn test:js:unit

Fix flaky Graph unit-tests

---

.github/workflows/ci.yml

[no-changeset]: CI changes
Test Plan: Look at GH CI

Add sccache configuration to GH actions

---

scripts/enforce-changeset.js

Test Plan:
N/A
[no-changeset]: change changeset

Fix enforce changeset script

---

.github/workflows/ci.yml

Test Plan:
GH actions
[no-changeset]: Tests

Cache `cargo test` rust compilation outputs

---

.changeset/tricky-bats-wash.md

Changeset for feature-flags PR
https://github.com/atlassian-labs/atlaspack/pull/581

add changeset

---

benchmarks/three-js/.parcelrc
benchmarks/three-js/scripts/build.mjs

Running benchmark run from the temp directory
[no-changeset]: Benchmarks aren't published

Fix: Running benchmarks from temp directory

---

.changeset/nasty-files-own.md
crates/atlaspack_vcs/src/lib.rs
packages/core/integration-tests/test/vcs-cache.js

Fix bug related to rename handling
Test Plan: cargo test / yarn test:integration

Add more VCS cache tests and fix bug

---

docs/Atlaspack-API/Configuration-Guide.md
docs/Atlaspack-API/README.md

[no-changeset]: Another PR to improve our docs.
Created through _multiple iterations_ with Cursor AI assistance + reference to [Parcel API documentation](https://parceljs.org/features/parcel-api/ )
----
As mentioned in previous [PR](https://github.com/atlassian-labs/atlaspack/pull/624)
> 
Over the upcoming weeks, I'll try to improve our docs by leveraging AI tools and also checking what is available in the Parcel website. Things may change/evolve over time as I learn how to best leverage tools; eventually we could explore tools that could update/auto-generate documentation as we make changes.

[no changeset] introduce API docs

---

CONTRIBUTING.md
docs/features/Conditional Bundling.md
packages/examples/conditional-bundling/README.md
packages/examples/conditional-bundling/package.json

Update technical docs for conditional imports based on PR suggestions and feedback. This is a follow-up to #628, see there for more context.
[no-changeset]: docs change

Update conditional bundling docs

---

.changeset/popular-pianos-pretend.md
crates/node-bindings/src/optimizers/inline_requires_optimizer.rs
packages/core/integration-tests/test/inline-requires.js
packages/optimizers/inline-requires/src/InlineRequires.js

Cleans-up feature-flag that has been rolled-out internally.
Test Plan: N/A

Clean-up inline requires multi-threading

---

.changeset/smooth-impalas-sneeze.md

[no-changeset]: N/A
Added in https://github.com/atlassian-labs/atlaspack/pull/682

Fix changeset syntax smooth-impalas-sneeze

---

packages/core/core/src/public/BundleGroup.js
packages/core/core/src/public/Config.js
packages/core/core/src/public/Environment.js
packages/core/core/src/public/MutableBundleGraph.js
packages/core/core/src/public/PluginOptions.js
packages/core/core/src/public/Target.js
packages/core/logger/src/Logger.js
packages/utils/events/src/Disposable.js

Provide relevant context and motivation behind the change, if any
Describe the solution and changes you have made
[no-changeset]: Will do in parent PR

Class properties converted from comments

---

packages/core/build-cache/src/serializer.ts
packages/core/codeframe/src/codeframe.ts
packages/core/feature-flags/src/index.ts
packages/utils/domain-sharding/src/index.ts
packages/utils/domain-sharding/test/index.test.ts
packages/utils/events/src/ValueEmitter.ts

Fix type errors for layer 0:
- @atlaspack/events
- @atlaspack/feature-flags
- @atlaspack/diagnostic
- @atlaspack/build-cache
- @atlaspack/codeframe
- @atlaspack/markdown-ansi
- @atlaspack/domain-sharding

Migrate layer 0

---

packages/core/build-cache/package.json
packages/core/build-cache/src/serializer.ts
packages/core/codeframe/src/codeframe.ts
packages/core/codeframe/src/emphasize.d.ts
packages/core/codeframe/src/slice-ansi.d.ts
packages/core/core/package.json
packages/core/feature-flags/src/index.ts
packages/core/graph/package.json
packages/core/utils/package.json
packages/core/workers/package.json
packages/reporters/dev-server-sw/package.json
packages/reporters/dev-server/package.json
packages/transformers/less/package.json
packages/transformers/less/src/LessTransformer.ts
packages/utils/node-resolver-core/test/resolver.ts
yarn.lock

Fix ts errors

---

packages/core/core/test/Atlaspack.test.ts
packages/core/core/test/Environment.test.ts
packages/core/test-utils/src/.parcelrc-no-reporters
packages/core/test-utils/src/paths.ts
packages/core/test-utils/src/utils.ts
packages/core/workers/src/process/ProcessWorker.ts
packages/core/workers/src/threads/ThreadsWorker.ts
packages/core/workers/src/web/WebWorker.ts

[no-changeset]: TypeScript Migration

TypeScript: Path to worker threads

---

package.json
packages/core/workers/test/workerfarm.test.js
packages/dev/babel-register/index.js
packages/utils/node-resolver-core/test/resolver.ts
packages/utils/node-resolver-core/tsconfig.json

[no-changeset]: TypeScript migration

TypeScript: Fixing worker unit tests

---

packages/core/core/src/AssetGraph.ts
packages/core/core/src/requests/AssetGraphRequest.ts
packages/core/core/src/requests/BundleGraphRequest.ts
packages/core/core/test/AssetGraph.test.ts
packages/core/core/test/RequestTracker.test.ts
packages/core/feature-flags/src/index.ts

Typescript - merge main

---

packages/core/test-utils/src/fsFixture.ts

[no-changeset]: Test changes
Test Plan: N/A

Fix types for test template builders

---

.changeset/fluffy-apes-relax.md
crates/atlaspack_plugin_transformer_html/src/html_dependencies_visitor.rs
crates/atlaspack_plugin_transformer_html/src/html_transformer.rs
packages/core/feature-flags/src/index.ts
packages/transformers/html/src/inline.ts

Cleaning up `inlineIsolatedScripts` feature flag, as it is fully rolled out internally.
Cleaning up `inlineIsolatedScripts` feature flag

Cleanup inlineIsolatedScripts feature flag

---

packages/dev/atlaspack-inspector/package.json
packages/dev/atlaspack-inspector/src/frontend/package.json

Fix inspector packages publishing

---

.github/workflows/release.yml

The container change in a previous commit did not help with the docker pull failure.
Reverting so we're back on the original versino.

Revert container image change

---

.changeset/seven-keys-call.md
packages/core/feature-flags/src/index.ts
packages/core/integration-tests/test/monolithic-bundler.ts
packages/core/utils/src/replaceBundleReferences.ts

Cleaning up `inlineStringReplacementPerf` flag as it has been proven to improve SSR build times
Describe the solution and changes you have made

Cleanup inline string replacement perf flag
