packages/core/integration-tests/test/atlaspack-query.js

This test is failing on CI, so we will skip it while looking at a solution in parallel
Skip failing graph query test

Skip failing test

---

.github/workflows/canary-release.yml

The canary release workflow was disabled when initially creating this repository. Now that we are public, we can proceed with testing the workflow.
Enabled the canary release workflow

Enable canary releases

---

.github/workflows/ci.yml

The upload step in the unit tests job was required for the repl build when it did not build its own dependencies, but that is no longer the case and therefore it can be removed.
Remove upload step from unit tests in ci workflow

Remove upload in unit tests

---

packages/utils/atlaspack-watcher-watchman-js/src/wrapper.js

It's possible that the node.js watcher runs before the cache directory has been created.
Because of this we should create the cache directory before writing the snapshot file.

Prevent watcher from crashing on first run

---

packages/core/core/src/loadAtlaspackPlugin.js
packages/core/integration-tests/test/cache.js
packages/core/integration-tests/test/incremental-bundling.js
packages/core/integration-tests/test/integration/incremental-bundling/node_modules/atlaspack-bundler-test/index.js
packages/core/plugin/src/PluginAPI.js

Use the parcel plugin config symbol. This lets parcel plugins work with this tool and will allow all plugins from this tool to work with parcel.
In the future the atlaspack plugins can skip this symbol and just pass around objects that implement an interface. Adding the symbol into the plugin would be a compatibility layer.
Fix parcel plugin compatibility
* It'd be possible to handle both atlaspack and parcel symbols here, but that will mean plugins declared with `@atlaspack/plugin` will not work with parcel

Fix plugin forwards and backwards compatibility

---

.github/workflows/release.yml
.npmrc

It is quite common for the Atlassian registry to be committed into the yarn lockfile instead of the yarn registry. This will result in failing installs for anyone outside of Atlassian.
Add an `.npmrc` file that specifies the yarn registry so it is always used. Once yarn is upgraded to v2+, we can replace `.npmrc` with a `yarnrc.yml` config file.

Use yarn registry

---

packages/transformers/react-refresh-wrap/src/helpers/helpers.js

Quick bugfix for an issue that can occur in some cases, where the transformer has run but the runtime has not. We can handle this pretty trivially by making sure both versions are set before erroring.

Only error if versions don't match in react refresh

---

.gitignore
packages/migrations/parcel-to-atlaspack/README.md
packages/migrations/parcel-to-atlaspack/package.json
packages/migrations/parcel-to-atlaspack/src/bin.ts
packages/migrations/parcel-to-atlaspack/src/cli.ts
packages/migrations/parcel-to-atlaspack/src/migrations/diff.ts
packages/migrations/parcel-to-atlaspack/src/migrations/migrate-package-json.ts
packages/migrations/parcel-to-atlaspack/src/migrations/migrate-parcelrc.ts
packages/migrations/parcel-to-atlaspack/src/migrations/package-json/migrate-config-fields.ts
packages/migrations/parcel-to-atlaspack/src/migrations/package-json/migrate-dependencies.ts
packages/migrations/parcel-to-atlaspack/src/migrations/package-json/migrate-engines-field.ts
packages/migrations/parcel-to-atlaspack/src/migrations/package-json/sort-package-json-field.ts
packages/migrations/parcel-to-atlaspack/src/tsconfig.json
packages/migrations/parcel-to-atlaspack/tsconfig.json
yarn.lock

It is currently tedious to migrate from Parcel to Atlaspack, as there are several parts of a codebase that need to change. This change introduces a CLI to automate some of the migration process.
Add a `@atlaspack/parcel-to-atlaspack` package to expose a global `parcel-to-atlaspack` command that makes these changes:
**.parcelrc**
* Rename to `.atlaspackrc`
* Update any `@parcel/` plugin references to `@atlaspack/`
**package.json**
* Update `engines.parcel` to `engines.atlaspack`
* Update `@parcel/` plugin configurations to `@atlaspack/`
* Update `parcel` and `@parcel/` dependencies to `@atlaspack`

Add atlaspack migration package

---

packages/core/core/src/requests/AssetGraphRequestRust.js

Fix native asset graph compatibility with legacy js asset graph.
- Added mapping for bundle behaviour in `getAssetGraph`
- Added mapping for source type in `getAssetGraph`

Fix enum mapping for bundleBehaviour and sourceType

---

crates/atlaspack/src/requests/asset_graph_request.rs
crates/atlaspack_core/src/types/asset.rs
crates/atlaspack_plugin_resolver/src/atlaspack_resolver.rs
crates/atlaspack_plugin_transformer_js/src/transformer.rs
packages/core/integration-tests/test/javascript.js

Fix more native test scenarios. 144/278 now passing. 
- Merging duplicate dependencies instead of adding them to the graph
- I think ideally we'll remove duplicate deps at some point but I want to avoid changing the transformer as it's still used outside of v3
- Add correct default for `Asset.is_source`
- Add correct default for `Asset.is_bundle_splittable`
- Add correct empty file resolution to the default resolver plugin
- Fix built-in resolution to return empty file rather than excluded

Fix more native test scenarios

---

packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js
packages/packagers/js/src/ScopeHoistingPackager.js

This change adds a fast-path to `ScopeHoistingPackager::needsDefaultInterop`.
We have found that up to 50% of the build time can be spent on this function. If we force the default interop to be true, we can skip this function entirely.
The impact on production bundles from real applications seems minimal and the build time improvement is very significant.

Add faster packager feature-flag

---

packages/migrations/parcel-to-atlaspack/src/migrations/migrate-parcelrc.ts

Currently the migration cli will rename all files that start with `.parcelrc` to `.atlaspackrc` which will cause many files to be overwritten. For example, two files named `.parcelrc` and `.parcelrc-customsuffix` will both be renamed as `.atlaspackrc`.
Retain the suffix when renaming `.parcelrc` files

Retain .parcelrc suffix in migration cli

---

crates/atlaspack/src/atlaspack.rs
crates/atlaspack/src/plugins/config_plugins.rs
crates/atlaspack/src/test_utils.rs
crates/atlaspack_plugin_rpc/src/nodejs/rpc_conn_nodejs.rs
crates/atlaspack_plugin_rpc/src/nodejs/rpc_conns_nodejs.rs
crates/atlaspack_plugin_rpc/src/plugin/transformer.rs
crates/atlaspack_plugin_rpc/src/rpc_host.rs
crates/node-bindings/src/atlaspack/atlaspack.rs
packages/core/core/src/atlaspack-v3/AtlaspackV3.js
packages/core/core/src/atlaspack-v3/plugins/Resolver.js
packages/core/core/src/atlaspack-v3/plugins/index.js
packages/core/core/src/atlaspack-v3/worker/worker.js
packages/core/integration-tests/test/atlaspack-v3.js

This PR adds the ability for the Nodejs context to initialize Transformer plugins. They currently don't do anything other than resolve, initialize & store the target transformer plugin 
- removed `AtlaspackV3.build()` because it's currently unused
- expanded `NodejsWorker` to include `transformerRegister()` method
- Used to resolve and register a transformer plugin within the nodejs context
- injecting `RpcWorker` into `RpcTransformerPlugin`
- calling `transformerRegister` when `RpcTransformerPlugin` is initialized

[V3] Registering transformer plugins

---

packages/core/core/src/requests/AssetGraphRequestRust.js
packages/core/integration-tests/test/javascript.js

For some reason, `Dependency.symbols` is expected to always be a Map (even if empty) but only when scope hoisting is enabled. We should definitely address this and make things more consistent between the two modes (or unify them completely) when we revisit packaging, however I think we should just keep consistent with V2 for now. 
- Ensure `Dependency.symbols` is always a Map when scope hoisting is enabled
- Enable another test for V3
- Change symbols and loc to make them more consistent with V2 for easier diffing

[V3] Ensure Dependency.symbols when scope hoisting is enabled

---

packages/core/core/src/AtlaspackConfig.schema.js
packages/core/core/test/AtlaspackConfigRequest.test.js

Reasoning for there being validation is on https://github.com/parcel-bundler/parcel/issues/3397#issuecomment-521353931
Ultimately, we do not care about package names on NPM or whether there are published packages for plug-ins. Furthermore validation means incompatibility between parcel/atlaspack or adding code on both sides to support the renamed packages.

Remove package name validation

---

crates/atlaspack/src/requests/target_request.rs
crates/atlaspack_core/src/types/atlaspack_options.rs
packages/core/integration-tests/test/javascript.js
packages/core/integration-tests/test/scope-hoisting.js

We currently don't model unset values in the `default_target_options` so any unset values show up as their default which is false for booleans. We can implement sensible defaulting in future but for now we may as well let the JS layer pass in the values. 
- Honour passed in `default_target_optins.should_scope_hoist` value
- Enable a portion of the scope hoisting test suite

[V3] Fix scope hoisting value and enable scope hoisting tests

---

crates/atlaspack/Cargo.toml
crates/atlaspack/src/requests/asset_graph_request.rs

Since merging #31, some of the integration tests have been flaky. This was due to dependency insertion order not being respected when they are de-duplicated. 
Instead of a HashMap, use an IndexMap for deduping as that respects the insertion order of the dependencies.

[V3] Fix non-deterministic dependency order

---

crates/atlaspack_plugin_transformer_js/src/transformer.rs
crates/atlaspack_plugin_transformer_js/src/transformer/conversion.rs
packages/core/integration-tests/test/javascript.js
packages/core/integration-tests/test/scope-hoisting.js

While not idea, the packager expects that symbols are generated in a specific way, often containing the Asset id. Previous to this PR we were generating different names for these symbols which didn't line up with the packager and would produce invalid output. 
This PR also fixes an issue where re-export symbols didn't line up between the Asset and Dependency. 
- Use the Asset id directly in generated symbol names
- Fix re-export symbols on Assets
- Fix non-deterministic test
- Enable more scope-hoisting tests that are now passing

[V3] Ensure symbol names match up with Asset/Dep ids

---

Cargo.lock
crates/lmdb-js-lite/Cargo.toml
crates/lmdb-js-lite/src/lib.rs
crates/node-bindings/Cargo.toml
crates/node-bindings/src/lib.rs
crates/node-bindings/src/lmdb.rs
packages/core/cache/package.json
packages/core/cache/src/LMDBLiteCache.js
packages/core/cache/src/index.js
packages/core/cache/test/LMDBLiteCache.test.js
packages/core/rust/index.js.flow

Adds vendored LMDB parcel cache implementation.
The goal is to replace the LMDB cache back-end. There's no need for other implementation changing defaults for now.

Update with LMDB lite cache implementation

---

package.json
packages/core/integration-tests/package.json
packages/core/integration-tests/test/mochareporters.json
yarn.lock

The junit mocha reporter is unused and can be removed, as it's only really applicable for Bitbucket pipelines. Including junit introduces unnecessary dependencies and files when running in CI mode.
Remove the junit reporter and related dependencies

Remove junit mocha reporter

---

crates/atlaspack/src/requests/asset_graph_request.rs
crates/atlaspack_core/src/asset_graph.rs
crates/atlaspack_core/src/types/asset.rs
crates/atlaspack_core/src/types/dependency.rs
crates/atlaspack_core/src/types/environment/engines.rs
crates/atlaspack_plugin_transformer_js/src/transformer.rs
crates/atlaspack_plugin_transformer_js/src/transformer/conversion.rs
packages/core/core/src/requests/AssetGraphRequestRust.js
packages/core/integration-tests/test/javascript.js

We must use string ids that are 16 characters long, otherwise we may produce invalid bundles when the ids are less than 16 characters. This issue occurs during scope hoisting, as it will no longer replace dependencies from the hardcoded string lengths `{16,20}` specified in the `REPLACEMENT_RE` [regex](https://github.com/atlassian-labs/atlaspack/blob/main/packages/packagers/js/src/ScopeHoistingPackager.js#L40). This is the underlying reason why the integration tests in https://github.com/atlassian-labs/atlaspack/pull/36 were failing.
Replace `u64` with `String` for both asset and dependency ids

[V3] Use string ids

---

crates/atlaspack/src/requests/target_request.rs
crates/atlaspack/src/requests/target_request/package_json.rs
packages/core/integration-tests/test/scope-hoisting.js

Some tests were failing as they had a single browser (not an array) listed in their `package.json#browsers` field. Updating the `PackageJson` type fixes these scenarios. 
- Fixed parsing of single value browerslist queries in package.json
- Enabled 9 more scope-hoisting tests 
- Fixed non-deterministic test

[V3] Fix handling of single browser in browserslist query

---

crates/atlaspack/src/requests/target_request.rs
packages/core/core/src/requests/AssetGraphRequestRust.js
packages/core/integration-tests/test/javascript.js
packages/core/types-internal/src/index.js

When multiple targets are specified, v3 does not correctly insert enough asset groups. This occurs as the id generated in `nodeFromAssetGroup` includes an environment id, which was previously missing. When `addNodeByContentKeyIfNeeded` was called shortly thereafter, the id would be considered the same for all targets due to the missing environment id. In addition to this, the default values for builtin targets were not preserved.
* Add environment id on the JavaScript side, as it is not currently needed on the Rust side and would involve changing several structures to omit default values
* Merge default builtin target values when parts of a builtin config are specified to match v2 behaviour and add corresponding unit tests

Fix default target merging and add env id

---

Cargo.lock
crates/atlaspack/Cargo.toml
crates/atlaspack/src/plugins/config_plugins.rs
crates/atlaspack/src/requests/asset_graph_request.rs
crates/atlaspack_core/src/asset_graph.rs
crates/atlaspack_core/src/types/asset.rs
crates/atlaspack_core/src/types/dependency.rs
crates/atlaspack_plugin_transformer_inline_string/Cargo.toml
crates/atlaspack_plugin_transformer_inline_string/src/inline_string_transformer.rs
crates/atlaspack_plugin_transformer_inline_string/src/lib.rs
crates/atlaspack_plugin_transformer_js/src/js_transformer.rs
crates/atlaspack_plugin_transformer_js/src/js_transformer/conversion.rs
packages/core/core/src/requests/AssetGraphRequestRust.js
packages/core/integration-tests/test/bundle-text.js
packages/core/integration-tests/test/integration/multiple-import-types/dynamic-inline.js
packages/core/integration-tests/test/integration/multiple-import-types/static-inline.js
packages/core/integration-tests/test/javascript.js

Some tests fail because we do not have an inline string transformer. These changes port the transformer to Rust and fix some pre-existing bugs that were highlighted with the change.
* Add `atlaspack_plugin_transformer_inline_string` crate
* Update plugins to use the rust inline string transformer when `@atlaspack/transformer-inline-string` is encountered
* Add missing `pipeline` to assets
* Add in missing `bundle_behavior` to dependencies
* Remove `has_symbols` in favour of `Option<Vec<Symbol>>` since there were a lot of inconsistencies and bugs around when it was set
* Use `source_asset_id` instead of `source_asset_path` for the hash to match v2
* Enable some `bundle-text:` tests, and refactor a couple from the JavaScript suite into here

[V3] Add inline string transformer

---

crates/atlaspack/src/requests/asset_graph_request.rs
crates/atlaspack_core/src/asset_graph.rs
crates/atlaspack_core/src/plugin/reporter_plugin/composite_reporter_plugin.rs
crates/atlaspack_filesystem/src/in_memory_file_system.rs
crates/atlaspack_filesystem/src/os_file_system/canonicalize.rs
crates/atlaspack_monitoring/src/crash_reporter.rs
crates/atlaspack_monitoring/src/sentry_integration.rs
crates/atlaspack_monitoring/src/tracer.rs
crates/atlaspack_plugin_resolver/src/atlaspack_resolver.rs
crates/atlaspack_plugin_transformer_inline_string/src/inline_string_transformer.rs
crates/atlaspack_plugin_transformer_js/src/js_transformer.rs
crates/atlaspack_plugin_transformer_js/src/js_transformer/conversion.rs
crates/atlaspack_plugin_transformer_js/src/js_transformer/conversion/dependency_kind.rs
crates/atlaspack_plugin_transformer_js/src/js_transformer/conversion/symbol.rs
crates/atlaspack_plugin_transformer_raw/src/raw_transformer.rs
crates/lmdb-js-lite/src/lib.rs
crates/lmdb-js-lite/src/writer.rs
packages/transformers/js/core/src/dependency_collector.rs
packages/transformers/js/core/src/env_replacer.rs
packages/transformers/js/core/src/global_replacer.rs
packages/transformers/js/core/src/node_replacer.rs
packages/transformers/js/core/src/test_utils.rs
packages/transformers/js/core/src/typeof_replacer.rs
packages/utils/node-resolver-rs-old/src/url_to_path.rs
packages/utils/node-resolver-rs/src/url_to_path.rs

There are some inconsistencies in the test module name
Standardise on `mod tests` for unit tests as noted in official Rust documentation

Use tests as module name

---

Cargo.lock
crates/atlaspack/Cargo.toml
crates/atlaspack/src/plugins/config_plugins.rs
crates/atlaspack_plugin_transformer_json/Cargo.toml
crates/atlaspack_plugin_transformer_json/src/json_transformer.rs
crates/atlaspack_plugin_transformer_json/src/lib.rs
packages/core/integration-tests/test/json.js
packages/core/integration-tests/test/json5.js

These changes port the json transformer to Rust so that more functionality works in v3
* Add `atlaspack_plugin_transformer_json` crate
* Use json transformer when `@atlaspack/transformer-json` is encountered
* Enable json and json5 integration tests

[V3] Add json transformer

---

Cargo.lock
crates/atlaspack_monitoring/Cargo.toml
crates/atlaspack_monitoring/src/tracer.rs

The `tracing_subscriber` crate does not appear to output any logs unless a filter is specified. These changes apply a filter using the default env `RUST_LOG` so that it can be used like so:
```
ATLASPACK_TRACING_MODE=stdout RUST_LOG=debug yarn test:integration
```
Add a filter to std tracing based on the default env

Read RUST_LOG for std tracing

---

Cargo.lock
crates/atlaspack/Cargo.toml
crates/atlaspack/src/plugins/config_plugins.rs
crates/atlaspack/src/requests/asset_graph_request.rs
crates/atlaspack/src/requests/asset_request.rs
crates/atlaspack_core/src/types/asset.rs
crates/atlaspack_core/src/types/file_type.rs
crates/atlaspack_filesystem/src/in_memory_file_system.rs
crates/atlaspack_filesystem/src/lib.rs
crates/atlaspack_filesystem/src/os_file_system.rs
crates/atlaspack_plugin_resolver/src/atlaspack_resolver.rs
crates/atlaspack_plugin_transformer_image/Cargo.toml
crates/atlaspack_plugin_transformer_image/src/image_transformer.rs
crates/atlaspack_plugin_transformer_image/src/lib.rs
crates/node-bindings/src/atlaspack/atlaspack.rs
crates/node-bindings/src/atlaspack/file_system_napi.rs
crates/node-bindings/src/atlaspack/mod.rs
crates/node-bindings/src/file_system/mod.rs
crates/node-bindings/src/lib.rs
crates/node-bindings/src/resolver.rs
crates/node-bindings/src/resolver_old.rs
packages/core/core/src/atlaspack-v3/fs.js
packages/core/integration-tests/test/data-url.js
packages/core/integration-tests/test/image.js
packages/core/integration-tests/test/integration/image-exif/resized.html
packages/core/integration-tests/test/integration/image-exif/resized.js
packages/core/integration-tests/test/integration/image-multiple-queries/index.css
packages/core/integration-tests/test/integration/image-multiple-queries/index.js
packages/packagers/js/package.json

These changes port the image transformer to Rust so that more functionality works in v3. It also removes the overhead of calling into JavaScript plugins by using Rust directly.
* Represent `Code` type as bytes instead of a string for binary data
* Add `atlaspack_plugin_transformer_image` crate which supports most of the pre-existing types in the original image transformer. Note that the sharp config file is not supported since it uses a different underlying implementation. The `image` dependency may be revisited at a later time if necessary.
* Use image transformer when `@atlaspack/transformer-image` is encountered
* Add supported image file types to `FileType`
* Add `read` function to `FileSystem` trait to handle binary data when reading an asset file
* Add missing query to resolver …

[V3] Add image transformer

---

crates/atlaspack_core/src/types/environment/version.rs

Currently when `*` is provided as an engines version, v3 will fail to parse it. It is considered valid in the specification per [here](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines) so we should continue to support it:
> And, like with dependencies, if you don't specify the version (or if you specify "*" as the version), then any version of node will do.
Handle `*` engine versions

[V3] Support * engines version

---

Cargo.lock
crates/atlaspack_plugin_optimizer_inline_requires/Cargo.toml
crates/atlaspack_plugin_optimizer_inline_requires/src/inlining_visitor.rs
crates/atlaspack_plugin_optimizer_inline_requires/src/lib.rs
crates/node-bindings/Cargo.toml
crates/node-bindings/src/lib.rs
crates/node-bindings/src/optimizers/inline_requires_optimizer.rs
crates/node-bindings/src/optimizers/mod.rs
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js
packages/core/rust/index.js.flow
packages/core/rust/package.json
packages/core/rust/test/InlineRequiresNative.test.js
packages/optimizers/inline-requires/package.json
packages/optimizers/inline-requires/src/InlineRequires.js
packages/transformers/js/core/Cargo.toml
packages/transformers/js/core/src/dependency_collector.rs
packages/transformers/js/core/src/env_replacer.rs
packages/transformers/js/core/src/global_replacer.rs
packages/transformers/js/core/src/lib.rs
packages/transformers/js/core/src/node_replacer.rs
packages/transformers/js/core/src/runner.rs
packages/transformers/js/core/src/test_utils.rs
packages/transformers/js/core/src/typeof_replacer.rs
packages/utils/node-resolver-rs/benches/node_resolver_bench.rs

This change adds a rust implementation of the inline requires optimiser. This should avoid passing the AST back and forward to rust ; also since this is operating on large output files, the implementation might be a bit more efficient.
I've changed parts of the core SWC transformer wrapper code so that it can be used as a testing library on the new optimiser crate and so that it can run outputting source-maps.
At the moment there's waste, and even if source-maps aren't enabled they'll be partially generated. Some source-map file-naming might need to be patched as well as an anonymous file name is used.
The motivation for this change is to improve performance of the packaging phase of bundling.
There are no integration tests for inline requires that I could find.
There's a minor difference …

Add initial rust inline requires optimiser implementation

---

packages/core/conditional-import-types/index.d.ts
packages/core/conditional-import-types/package.json
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js
packages/examples/conditional-bundling/package.json
packages/examples/conditional-bundling/serve.js
packages/examples/conditional-bundling/src/async-feature-disabled.ts
packages/examples/conditional-bundling/src/async-feature-enabled.ts
packages/examples/conditional-bundling/src/feature-disabled.ts
packages/examples/conditional-bundling/src/feature-enabled.ts
packages/examples/conditional-bundling/src/feature-ui-disabled.tsx
packages/examples/conditional-bundling/src/feature-ui-enabled.tsx
packages/examples/conditional-bundling/src/index.html
packages/examples/conditional-bundling/src/index.tsx
packages/examples/conditional-bundling/src/lazy-component.tsx
packages/examples/conditional-bundling/src/regular-dynamic-import.ts
packages/examples/conditional-bundling/src/regular-import.ts
packages/examples/conditional-bundling/tsconfig.json
packages/examples/conditional-bundling/types.d.ts
packages/transformers/js/core/src/dependency_collector.rs
packages/transformers/js/core/src/lib.rs
packages/transformers/js/src/JSTransformer.js
yarn.lock

Add the conditional bundling API. By adding the API outside of the feature flag, we can start with simple no-op behaviour (making the return value the false branch of the condition). I'll follow up with iterative PRs to add the conditional behaviour behind the feature flag.
New import called `importCond` which (when implemented) will allow developers to conditionally load _sync_ dependencies based on the result of the condition param.

Add no-op importCond API

---

packages/core/core/src/resolveOptions.js
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js
yarn.lock

Adds flag to switch between lmdb-js and lmdb-js-lite
This is to roll-out the rust wrapper more widely to CLI usages.

Add flag to switch between LMDB backends

---

packages/core/core/src/applyRuntimes.js
packages/core/integration-tests/test/bundler.js
packages/core/integration-tests/test/workers.js

A while back in Parcel, we [reversed the order](https://github.com/parcel-bundler/parcel/pull/8837) that runtimes were processed in, so that child runtimes could be processed before parent bundles who would need to know about them. That didn't quite cut it, so we moved to [reverse topological order](https://github.com/parcel-bundler/parcel/pull/8981).
This works fine for Jira, but in Confluence it causes an issue where a bundle gets loaded thinking that some of its dependencies are already loaded when they aren't.
We thought we'd fixed this with `connections.reverse()`, but that doesn't _actually_ restore topological order, and it seems that Confluence has found the edge case.
The fix here is to actually restore topological order, by processing the bundles in reverse, and then …

Sort the connections back into topological order after traversing runtimes

---

packages/core/core/src/Atlaspack.js

This improves runtime of running integration tests at the moment.
A better fix is to pre-compile these tests.

Limit number of rust threads on tests to 2

---

Cargo.lock
crates/atlaspack_core/src/types/asset.rs
crates/atlaspack_core/src/types/dependency.rs
crates/atlaspack_plugin_transformer_html/Cargo.toml
crates/atlaspack_plugin_transformer_html/src/lib.rs
packages/transformers/html/package.json
packages/transformers/html/src/HTMLTransformer.js
packages/transformers/html/test/HTMLTransformer.test.js

There are 2 changes:
* Add rust HTML transformer and start to write test-suite for JavaScript HTML transformer
* Fix asset ID alias
HTML transformer implementation is not complete. I chose to use Servo's HTML parser. There's just a very barebones set-up at the moment.
Please see the commit messages for justifications. I'm removing the "non zero u32" alias because it's unused and incompatible with the current code. So I'd rather alias to string until we port all code to use u32.
We shouldn't have an alias that can't be used on the current code. A change to make the IDs u32 should be applied globally to everything.

Start work on Rust HTML transformer

---

crates/atlaspack/src/request_tracker/request_graph.rs
crates/atlaspack/src/request_tracker/request_tracker.rs
crates/atlaspack/src/requests/asset_graph_request.rs
crates/atlaspack/src/requests/asset_request.rs
crates/atlaspack_core/src/types/invalidation.rs

This change wires-up passing cache invalidation data from the asset request into the request tracker.
It also removes one seemingly unnecessary generic type we had around request graph nodes.

Partially wire-up cache invalidation forwarding

---

crates/atlaspack/src/requests/target_request.rs
crates/atlaspack/src/requests/target_request/package_json.rs
packages/core/integration-tests/test/javascript.js

The original error was a parsing issue due to type mismatching in `package.json`. This code resolves it and reveals an issue with the asset graph being incorrectly built in case multiple targets are stated. The tests now fail with the error "Bundles must have unique name. Conflicting names:". This will be fixed in a separate PR.

Resolve serde error when reading package json browser fields

---

packages/transformers/html/test/HTMLTransformer.test.js

We didn't test for inline scripts before and it will help to have a test for both the v2 and v3 transformer, the v3 test will be written in a separate PR.

Add test for html transformer in case of an inline script

---

crates/atlaspack_config/src/map/named_pipelines_map.rs

When you have named pipelines like the following: `data-url:./img.svg`, the named pipeline (`data-url` in this case) should be executed after the normal file type based pipeline. 
This was picked up as part of the node plugin work. 
- Run named pipelines after file type based pipelines

Ensure named pipelines run after file match pipelines

---

crates/atlaspack_plugin_rpc/src/nodejs/rpc_conn_nodejs.rs
crates/atlaspack_plugin_rpc/src/nodejs/rpc_conns_nodejs.rs
crates/atlaspack_plugin_rpc/src/plugin/transformer.rs
crates/atlaspack_plugin_rpc/src/rpc_host.rs
packages/core/core/src/atlaspack-v3/worker/compat.js
packages/core/core/src/atlaspack-v3/worker/worker.js
packages/core/integration-tests/test/data-url.js
packages/core/integration-tests/test/javascript.js
packages/core/integration-tests/test/output-formats.js
packages/core/integration-tests/test/packager.js
packages/core/integration-tests/test/resolver.js
packages/core/integration-tests/test/scope-hoisting.js
packages/core/integration-tests/test/svg.js

This PR adds basic Node JS plugin support to Atlaspack V3. I've stripped back the code to not bother handle dependencies at all. This requires a bunch more changes which I have done in [another branch](https://github.com/atlassian-labs/atlaspack/tree/node-plugin-html) but I'm not sure if we really want to continue supporting dependencies in JS plugins going forward. If we decide we'd like to add this feature we can follow up with that. 
For now this PR is enough to get a basic transformer like `@atlaspack/transformer-svg` working which I have enabled an integration test for in this PR. There's still a bunch more things to add like invalidations and source-maps but this is a good start. 
- [] Existing or new tests cover this change

Add basic Node JS plugin support

---

.vscode/launch.json
Cargo.lock
packages/core/integration-tests/test/conditional-bundling.js
packages/examples/conditional-bundling/package.json
packages/examples/conditional-bundling/serve.js
packages/examples/conditional-bundling/src/feature-ui-disabled.tsx
packages/examples/conditional-bundling/src/index.tsx
packages/transformers/js/core/Cargo.toml
packages/transformers/js/core/src/conditional_imports_fallback.rs
packages/transformers/js/core/src/dependency_collector.rs
packages/transformers/js/core/src/lib.rs
packages/transformers/js/core/src/test_utils.rs

Allows usage of importCond in jira with support for a condition. This allows us to actually use `importCond` functionally in production, without the bundling implementation.
- New module `ConditionalImportsFallback` to visit earlier than the dependency collector

Use inline requires when importCond flag is disabled

---

.github/workflows/release.yml

Fixing the release for `arm-unknown-linux-gnueabihf` by removing an unneeded build arg.
Dropping `-mfpu=neon`

Fix release arm-unknown-linux-gnueabihf

---

crates/atlaspack/src/plugins.rs
crates/atlaspack/src/plugins/config_plugins.rs
crates/atlaspack/src/requests/asset_graph_request.rs
crates/atlaspack/src/requests/asset_request.rs
crates/atlaspack_core/src/plugin/transformer_plugin.rs
crates/atlaspack_plugin_rpc/src/plugin/transformer.rs
crates/atlaspack_plugin_transformer_html/src/lib.rs
crates/atlaspack_plugin_transformer_image/src/image_transformer.rs
crates/atlaspack_plugin_transformer_inline/src/inline_transformer.rs
crates/atlaspack_plugin_transformer_inline_string/src/inline_string_transformer.rs
crates/atlaspack_plugin_transformer_js/src/js_transformer.rs
crates/atlaspack_plugin_transformer_js/src/js_transformer/conversion.rs
crates/atlaspack_plugin_transformer_json/src/json_transformer.rs
crates/atlaspack_plugin_transformer_raw/src/raw_transformer.rs

The PR achieves the following:
* implements logic to discover and process new assets with a queue
* adds unit tests for new functionality
* changes the transformers and pipeline APIs to allow for easier mocking and to no longer use hash keyword to avoid colliding with the standard library
The remaining work is to model the `AssetRequestOutput` and related function to update the new assets.

Change transformers to allow multiple assets in result

---

packages/core/core/src/RequestTracker.js
packages/core/core/test/RequestTracker.test.js
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js
packages/core/graph/src/ContentGraph.js
packages/core/graph/src/Graph.js

This should improve performance of handling filesystem events, since there won't be one graph traversal for every event. Since complexity of this particular section is reduced to be roughly linear we expect worst case performance of handling events to improve.

Don't clean-up orphaned nodes on every event

---

packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js
packages/packagers/js/src/ScopeHoistingPackager.js

Cleans-up a feature-flag that improved bundling performance by 30% by bailing-out earlier on default interop checks.

Clean-up faster packager feature-flag

---

packages/core/core/src/atlaspack-v3/worker/worker.js

ESM plugins are available under `module.default`
CJS plugins may be under `module.default.default`
Support both import patterns

Support loading CJS plugins

---

packages/core/cli/src/cli.js
packages/core/core/src/Atlaspack.js
packages/core/core/src/RequestTracker.js
packages/core/core/test/RequestTracker.test.js
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js
packages/core/feature-flags/test/feature-flags.test.js

This commit fixes several performance problems in the cache invalidation implementation. Overall, this improves performance of handling a large number of events from updating `node_modules` on a large application by 1500x.
The request graph stores a tasks, and their inter-dependencies, as well as their relationship with files. Relationship with files is used for cache invalidation.
There are a few problems with the current implementation:
* Cache invalidation performs `O(events * tasks)` amount of work. This is not fixed
* The "file above" invalidation type has extremely poor performance because even though the files are structured in a prefix tree sort of structure, the implementation is listing all incoming nodes and then iterating them to check for file-path matches. This means that …

Optimize request tracker cache invalidation

---

packages/core/core/src/Atlaspack.js
packages/core/core/src/resolveOptions.js
packages/packagers/js/src/ScopeHoistingPackager.js

PR https://github.com/atlassian-labs/atlaspack/pull/72 added a feature-flag to switch to the new LMDB back-end, however that flag isn't correctly read because it is not set when resolving options.
This PR changes the feature-flags code to set feature-flags before anything else.
`AFB-786`

Fix reading feature-flags when resolving options

---

crates/atlaspack_plugin_rpc/src/plugin/resolver.rs
crates/atlaspack_plugin_rpc/src/rpc/resolver.rs
packages/core/core/src/atlaspack-v3/worker/worker.js

- Added `Resolver.loadConfig()`
- Added partial `PluginOptions`
- Added partial `PluginConfig`
- [TEMP] Initialize `NodeFS` for workers
- [TEMP] Initialize `PackageManger` in worker
NOTE: This would not pass integration tests because the `NodeFS` does not work there. Discussion on this might be to rewrite the integration tests to use the real FS for integration tests

V3: Resolver.loadConfig() and some arguments

---

Cargo.lock
crates/atlaspack/Cargo.toml
crates/atlaspack/src/plugins/config_plugins.rs
crates/atlaspack_plugin_transformer_yaml/Cargo.toml
crates/atlaspack_plugin_transformer_yaml/src/lib.rs
crates/atlaspack_plugin_transformer_yaml/src/yaml_transformer.rs
packages/core/integration-tests/test/yaml.js

These changes port the yaml transformer to Rust so that more functionality works in v3. It also removes the overhead of calling into JavaScript plugins by using Rust directly.
* Add `atlaspack_plugin_transformer_yaml` crate
* Use yaml transformer when `@atlaspack/transformer-yaml` is encountered
* Enable yaml tests

[V3] Add native yaml transformer

---

packages/core/integration-tests/test/macros.js
packages/core/package-manager/package.json
packages/optimizers/inline-requires/package.json
packages/optimizers/swc/package.json
yarn.lock

Bump SWC to 1.7.26, only where used from JavaScript.

Bump SWC to 1.7.26

---

packages/core/cli/src/cli.js

This commit adds a `--production` CLI flag to serve/watch commands, so that we can run them in production mode to debug or test production build outputs in local/watch builds.
Sometimes app developers might need to profile or debug their apps in production mode, for example for performance/load time debugging or to understand certain issues that might be only happening on production builds.
Currently when using the CLI, all `atlaspack serve` / `atlaspack watch` builds are development mode and all `atlaspack build` builds are production mode.
This commit adds a `--production` flag that is used to turn on production mode in the `watch` / `serve` commands.

Add --production for production mode serve/watch

---

packages/core/core/src/atlaspack-v3/worker/compat/asset-compat.js
packages/core/core/src/atlaspack-v3/worker/compat/asset-symbols.js
packages/core/core/src/atlaspack-v3/worker/compat/bitflags.js
packages/core/core/src/atlaspack-v3/worker/compat/dependency.js
packages/core/core/src/atlaspack-v3/worker/compat/environment.js
packages/core/core/src/atlaspack-v3/worker/compat/index.js
packages/core/core/src/atlaspack-v3/worker/compat/target.js
packages/core/core/src/atlaspack-v3/worker/worker.js
packages/core/rust/index.js.flow

All Resolvers in JFE now pass
- Added compat types for napi structures that need to be used in JavaScript
- `Dependency`
- `Environment`
- `Target`
- `MutableDependencySymbols`
- Added compat mappings for bit types (`BundleBehavior`, etc)

V3: Resolver API

---

crates/atlaspack_plugin_optimizer_inline_requires/src/lib.rs
packages/core/integration-tests/test/inline-requires.js

The rust inline requires visitor wasn't doing anything on output bundles because the `parcelRequire = ...` symbol isn't always an unresolved global.

Fix bug in inline requires

---

packages/core/core/src/AssetGraph.js

When building Confluence SSR with Atlaspack, `setRootConnections` fails with the following error:
> RangeError: Maximum call stack size exceeded
This is similar to the problem described [here](https://stackoverflow.com/questions/22123769/rangeerror-maximum-call-stack-size-exceeded-why) where we are adding too many nodes (117618) at once on the stack, which causes the failure.
Use a for of loop

Fix setRootConnections for large asset groups

---

packages/core/core/src/requests/ConfigRequest.js
packages/core/package-manager/src/installPackage.js
packages/core/utils/src/index.js
packages/dev/bundle-stats-cli/src/deep-imports.js
packages/dev/query/src/cli.js
packages/dev/query/src/deep-imports.js
packages/dev/repl/SimplePackageInstaller/index.js
packages/dev/repl/src/atlaspack/AtlaspackWorker.js
packages/dev/repl/src/components/helper.js
packages/runtimes/hmr/src/loaders/hmr-runtime.js

Some import sources hardcode the `.js` file extension as part of the path. This will not work when the source files are TypeScript, and thus have been removed in preparation for the [migration](https://github.com/atlassian-labs/atlaspack/pull/99).
Remove `.js` extensions from import sources

Remove import extensions

---

packages/core/core/src/projectPath.js
packages/core/core/test/requests/ConfigRequest.test.js

These changes are similar to https://github.com/atlassian-labs/atlaspack/pull/81 but instead uses code that has been applied in Confluence for a while. Specifically when the cwd and project root are different, paths within symbols and loc would be processed twice resulting in invalid paths.
Skip `toProjectPath` handling when the path is already relative from Atlaspack's point of view

Skip toProjectRoot relative paths when already relative

---

packages/core/core/src/SymbolPropagation.js

As discussed in the sync I will be doing a short series of obvious refactors to move us to a nicer `SymbolPropagation.js` version that will be slightly easier to maintain until we rewrite it in rust
Simple refactor removing some obvious code duplication and simplifying a for loop.

Remove egregious cases of code duplication in SymbolProp

---

packages/utils/babel-plugin-transform-contextual-imports/package.json
yarn.lock

#97 caused a dependency issue when introduced into Jira, as the version for @babel/helper-plugin-utils was broken.
This change pins @babel/helper-plugin-utils to the same version as core.

Fix bad version for @babel/helper-plugin-utils

---

packages/core/fs/src/MemoryFS.js
packages/core/test-utils/src/fsFixture.js
packages/core/utils/src/DefaultMap.js
packages/core/utils/src/dependency-location.js

Inline flow interfaces are not supported by the TypeScript codemod, and thus have been modified to be compatible with it.
* Extract out `DirEntry` and `Key` interface
* Inline `start` and `strings` types

Remove inline interfaces

---

Cargo.lock
crates/atlaspack/src/plugins/config_plugins.rs
crates/atlaspack/src/requests/asset_graph_request.rs
crates/atlaspack_core/src/asset_graph.rs
crates/atlaspack_core/src/types/asset.rs
crates/atlaspack_plugin_transformer_css/Cargo.toml
crates/atlaspack_plugin_transformer_css/src/css_transformer.rs
crates/atlaspack_plugin_transformer_css/src/css_transformer_config.rs
crates/atlaspack_plugin_transformer_css/src/lib.rs
crates/atlaspack_plugin_transformer_js/src/js_transformer.rs
packages/core/integration-tests/test/css-modules.js
packages/core/integration-tests/test/css.js

This PR improves the CSS transformer and makes changes to the asset graph request to support CSS modules. Most CSS features are now supported except for the following: 
- [CSS module composes](https://github.com/css-modules/css-modules/blob/master/docs/composition.md) which can be added later if needed.
- Config options
- exclude/include globs
- [custom-naming-patterns](https://parceljs.org/languages/css/#custom-naming-patterns)
- [custom-media-queries](https://parceljs.org/languages/css/#custom-media-queries)
- [pseudo-class-replacement](https://parceljs.org/languages/css/#pseudo-class-replacement)
None of which are currently used in AFM. 
- Support CSS transformer config loading
- Global CSS modules
- Dashed idents
- Consistent CSS module detection against v2
- Browserslist support for …

[V3] CSS improvements and fixes

---

packages/core/graph/src/AdjacencyList.js

The `AdjacencyList` class uses unnecessary doc types that aren't understood by the TypeScript codemod, so they have been removed in favour of listing the actual types.
Correctly annotate nodes, edges, and params types in the adjacency list

Annotate adjacency list types

---

package.json
packages/core/core/package.json
packages/core/core/src/Atlaspack.js
packages/core/core/test/RequestTracker.test.js
packages/core/core/test/requests/ConfigRequest.test.js
packages/core/fs/test/OverlayFS.test.js
packages/core/integration-tests/package.json
packages/core/package-manager/test/NodePackageManager.test.js
packages/core/test-utils/test/fsFixture.test.js
packages/core/workers/src/WorkerFarm.js
packages/core/workers/src/bus.js
packages/core/workers/src/child.js
packages/core/workers/src/core-worker.browser.js
packages/core/workers/src/process/ProcessWorker.js
packages/core/workers/src/threads/ThreadsWorker.js
packages/dev/eslint-plugin/test/utils.test.js

When migrating to TypeScript, all of the worker paths break due to the change in extension. Additionally, the babel dependency in the eslint plugin changes slightly and requires a filename in the tests.
* Resolve worker paths without an extension
* Use a public export name for the worker paths using the development condition
* Add filename to eslint parser

Fix worker paths and add missing filename

---

crates/atlaspack_plugin_resolver/src/atlaspack_resolver.rs

When global variables are returned from the resolver we create a virtual file for them to resolve to. This file path should be absolute otherwise the path_request will blow up. This behaviour is consistent with v2.

[V3] Return absolute file path for global resolve values

---

crates/atlaspack_plugin_rpc/src/nodejs/plugins/mod.rs
crates/atlaspack_plugin_rpc/src/nodejs/plugins/nodejs_rpc_resolver.rs
crates/atlaspack_plugin_rpc/src/nodejs/plugins/nodejs_rpc_transformer.rs
crates/atlaspack_plugin_rpc/src/nodejs/plugins/plugin_options.rs
packages/core/core/src/atlaspack-v3/worker/compat/mutable-asset.js
packages/core/core/src/atlaspack-v3/worker/worker.js

This PR works around/fixes a few small behaviours with JS plugin loading that was discovered while building JFE.
- Make `options.mode` available to Plugins
- Don't error when an AST isn't returned from `Transformer.generate`
- Implement `Asset.isASTDirty`
- Make the following methods noops for now
- `Asset.invalidateOn*`
- `Asset.getMap`

[V3] Fix broken/missing transformer plugin behaviours

---

packages/core/core/src/Atlaspack.js
packages/core/core/src/AtlaspackConfig.js
packages/core/core/src/PackagerRunner.js
packages/core/core/src/Transformation.js
packages/core/core/src/Validation.js
packages/core/core/src/applyRuntimes.js
packages/core/core/src/registerCoreWithSerializer.js
packages/core/core/src/requests/AtlaspackConfigRequest.js
packages/core/core/src/requests/BundleGraphRequest.js
packages/core/core/src/requests/DevDepRequest.js
packages/core/core/src/requests/PathRequest.js
packages/core/core/src/requests/ValidationRequest.js
packages/core/core/src/requests/WriteBundleRequest.js
packages/core/core/src/worker.js
packages/core/core/test/AtlaspackConfig.test.js
packages/core/core/test/AtlaspackConfigRequest.test.js

When running the TypeScript codemod, instances of the following code are left as is and later become errors:
```javascript
import type AtlaspackConfig, {LoadedPlugin} from './AtlaspackConfig';
```
> A type-only import can specify a default import or named bindings, but not both.
Make `AtlaspackConfig` a named export to avoid the error during the migration

Fix ambiguous atlaspack config imports

---

Cargo.lock
crates/atlaspack/Cargo.toml
crates/atlaspack/src/requests/target_request.rs
crates/atlaspack_core/src/types/atlaspack_options.rs

Prior to this change `should_optimize` would be set to true when a prod build occurred but `--no-optimize` was passed.

[V3] Handle should optimize false correctly

---

crates/atlaspack_contextual_imports/src/lib.rs
packages/core/integration-tests/test/conditional-bundling.js
packages/core/test-utils/src/utils.js
packages/examples/conditional-bundling/features.js
packages/examples/conditional-bundling/package.json
packages/examples/conditional-bundling/serve.js
packages/examples/conditional-bundling/src/index.html
packages/examples/conditional-bundling/src/index.tsx
packages/runtimes/js/src/JSRuntime.js
packages/transformers/js/core/src/lib.rs

We need a safe rollout when `globalThis.__MCOND` is not defined (if we mess something up on the control branch of the rollout). We also have an issue where some dependencies don't get loaded correctly when prod mode is on.
Two major changes here:
- Check if `globalThis.__MCOND` exists when configured, so we can have a safe rollout when feature flag is disabled
- Fix the dependency in scope hoisting, as we don't pick up the correct dep
I also added a new integration test and fixed some tests not using the correct data. This can probably allow some refactoring in the style of the new test. Dev mode is broken so I skip the test I fixed (as it's now red).

Change fallback behaviour for __MCOND and fix dependency for runtime

---

Cargo.lock
crates/atlaspack_core/src/plugin/transformer_plugin.rs
crates/atlaspack_plugin_rpc/src/nodejs/plugins/nodejs_rpc_transformer.rs
crates/atlaspack_plugin_rpc/src/testing.rs
crates/atlaspack_plugin_transformer_css/src/css_transformer.rs
crates/atlaspack_plugin_transformer_html/src/html_transformer.rs
crates/atlaspack_plugin_transformer_image/src/image_transformer.rs
crates/atlaspack_plugin_transformer_inline/src/inline_transformer.rs
crates/atlaspack_plugin_transformer_inline_string/src/inline_string_transformer.rs
crates/atlaspack_plugin_transformer_js/Cargo.toml
crates/atlaspack_plugin_transformer_js/src/js_transformer.rs
crates/atlaspack_plugin_transformer_json/src/json_transformer.rs
crates/atlaspack_plugin_transformer_raw/src/raw_transformer.rs
crates/atlaspack_plugin_transformer_yaml/src/yaml_transformer.rs

Transformers currently require a mutable reference. This PR changes them to be immutable. The one case of mutation was migrated to interior mutability.
This is required because plugins are shared across threads and this allows us to avoid wrapping `TransformerPlugin`s in a `RwLock`.

V3: Moving Transformers from "&mut self" to "&self"

---

packages/core/core/src/atlaspack-v3/worker/worker.js

Temporarily use require.resolve() as the resolve() function in JavaScript workers

V3: Temporarily use require.resolve() as Transformer resolve() function for JS workers

---

crates/atlaspack_napi_helpers/src/js_callable/js_callable.rs
crates/atlaspack_plugin_rpc/src/nodejs/plugins/nodejs_rpc_resolver.rs
crates/atlaspack_plugin_rpc/src/nodejs/plugins/nodejs_rpc_transformer.rs
crates/atlaspack_plugin_rpc/src/nodejs/rpc/nodejs_rpc_worker.rs
crates/node-bindings/src/atlaspack/file_system_napi.rs
crates/node-bindings/src/atlaspack/package_manager_napi.rs

- Handling `.unwrap()` in `JsCallable` by throwing the Rust error back to JavaScript
- Removed the `JsCallable::call` (without return) methods because they are unused and shouldn't be used due to footguns
- Renamed `JsCallable::call_with_return` to `JsCallable::call`

V3: Slightly better error handling for jscallable

---

Cargo.lock
crates/atlaspack/src/plugins/config_plugins.rs
crates/atlaspack_plugin_resolver/Cargo.toml
crates/atlaspack_plugin_resolver/src/atlaspack_resolver.rs

This PR fixes a couple of things in the default resolver plugin which are required for jira-spa builds. 
- Add config loading to support enabling of the package exports resolver flag
- Fix built in polyfill resolution for the `string_decoder` module

[V3] Fix string_decoder builtin, Support package_exports config

---

crates/atlaspack_plugin_optimizer_inline_requires/src/inlining_visitor.rs
crates/atlaspack_plugin_optimizer_inline_requires/src/lib.rs
packages/core/integration-tests/test/inline-requires.js
packages/core/rust/test/InlineRequiresNative.test.js

When adding rust inline requires I choose not to include `(0, ...)` wrappers as we didn't understand where that would cause problems.
Apparently this is required due to handling of `new ...` expressions.
The reason this is required is due to the following output being treated
differently:
```js
const value = { default: class Something {} };
new value.default()
// => this is instance of Something
```
However:
```js
const getValue = () => value;
new getValue().default()
// => this fails because `getValue` is not a constructor
```
And:
```js
new (0, getValue()).default()
// => this works and uses `default` as the constructor
```

Fix inline requires problem with (0, ...)

---

packages/core/core/src/atlaspack-v3/worker/worker.js

Ideally, we'd use the real resolve pipeline for transformers that call the `resolve` API, however this is a bit of work and it's not clear if we really need it going forward. Moving to `module.createRequire` fixes some broken cases in Jira builds in the meantime though.

[V3] Fix transform resolve function

---

packages/core/cli/src/cli.js
packages/core/core/src/Atlaspack.js
packages/core/core/src/requests/AssetRequest.js
packages/core/utils/test/PromiseQueue.test.js

Adds a command to build asset graph from the command-line and write to the cache.
This can be used for testing or benchmarking this section of the tool.

Add CLI debug build asset graph command

---

crates/atlaspack_plugin_rpc/src/nodejs/plugins/nodejs_rpc_resolver.rs
crates/atlaspack_plugin_rpc/src/nodejs/plugins/nodejs_rpc_transformer.rs

When encountering errors in the native rewrite, seeing `RpcNodejsResolverPlugin` or `RpcTransformerPlugin` is not useful in the stack trace as it is missing the actual plugin name it has loaded.
Update the `Debug` implementations in the rpc transformer and resolver to include the package name

V3: Improve resolver and transformer debug

---

packages/core/core/src/atlaspack-v3/worker/compat/dependency.js

The compatibility layer for a dependency uses the incorrect `resolveFrom` value that gets set at the start of a resolver in JavaScript.
```javascript
export class ResolverRunner {
async resolve(dependency: Dependency): Promise<ResolverResult> {
let dep = getPublicDependency(dependency, this.options);
// ...
}
}
```
```javascript
export class Dependency implements IDependency {
get resolveFrom(): ?string {
return fromProjectPath(
this.#options.projectRoot,
this.#dep.resolveFrom ?? this.#dep.sourcePath,
);
}
}
```
Rust plugins currently fallback to the correct resolve from value, and thus do not need to have any of this logic for the time being.
Fallback to `sourcePath` for dependency `resolveFrom`

V3: Fix resolveFrom value

---

packages/core/core/src/atlaspack-v3/WorkerPool.js
packages/core/core/test/atlaspack-v3/WorkerPool.test.js
packages/core/core/test/atlaspack-v3/worker-error.js

The worker pool does not log errors when the worker fails to startup, which makes debugging / running inspectors difficult when they timeout for other reasons
* Listen to worker errors when creating a worker
* Recreate worker from passed in worker path

V3: Reject worker errors

---

packages/core/core/src/RequestTracker.js
packages/core/core/src/requests/AssetGraphRequest.js
packages/core/package-manager/src/installPackage.js
packages/core/utils/src/PromiseQueue.js
packages/core/utils/test/PromiseQueue.test.js

The current `PromiseQueue` API is build such that the following code will raise an unhandled rejection error:
```js
const queue = new PromiseQueue();
queue.add(() => Promise.reject(new Error('foo')));
await queue.run();
```
For this reason, most of the codebase uses `PromiseQueue#add` with a catch block around the promise, including its own tests.
As such, the correct usage of the API is:
```js
const queue = new PromiseQueue();
queue.add(() => Promise.reject(new Error('foo'))).catch((err) => {});
await queue.run();
```
All the other usages, that haven't been modified by this commit, were missing this handling and may lead to unhandled rejections crashing threads/workers.
This commit changes the API so that this can't happen, the API can't trigger unhandled exceptions anymore, and the …

´Fix PromiseQueue to remove unhandled rejections

---

crates/atlaspack_plugin_transformer_css/src/css_transformer.rs
packages/core/integration-tests/test/css-modules.js

This PR adds supports for CSS composes of local and global variables. Note I have not yet added support for the more complex composing of classes from dependencies which is not known to be used internally.

Add support for CSS modules composes

---

benchmarks/three-js/scripts/build.mjs
crates/atlaspack/src/requests/asset_request.rs
crates/atlaspack/src/requests/target_request.rs
crates/atlaspack_core/src/plugin/resolver_plugin.rs
crates/atlaspack_core/src/types/asset.rs
crates/atlaspack_core/src/types/environment/engines.rs
crates/atlaspack_plugin_transformer_js/src/js_transformer.rs
packages/core/core/src/atlaspack-v3/AtlaspackV3.js
packages/core/integration-tests/test/bundler.js
packages/core/integration-tests/test/integration/formats/commonjs-helpers/package.json
packages/core/integration-tests/test/integration/swc-helpers-library/package.json
packages/core/integration-tests/test/javascript.js
packages/core/integration-tests/test/output-formats.js
packages/core/integration-tests/test/workers.js
packages/core/test-utils/src/utils.js
packages/examples/kitchen-sink/package.json
packages/transformers/js/package.json
yarn.lock

During the recent [swc bump](https://github.com/atlassian-labs/atlaspack/pull/171), v3 broke running internally as the `@swc/helpers/_/_call_super` module could not be found. This issue occurred for a few reasons that these changes try to rectify:
* The `@swc/helpers` dependency was not updated to the latest version in the js transformer
* Integration tests default to the latest features, so any polyfills and modules added by swc are not accurately verified in the test suite
* The rust default browser engines specified `> 0.25%` browsers which is the same as the v2 environment defaults, however usually the defaults from the v2 target request are used and these are different
* Add a test case that replicates the issue encountered internally with missing helpers
* Bump `@swc/helpers` …

Fix default engines handling

---

packages/core/integration-tests/test/javascript.js
packages/core/integration-tests/test/scope-hoisting.js

I believe these tests work now, they pass on my local with `ATLASPACK_V3=true` so I want to test it in CI.

turn tests for optional deps on for v3

---

packages/core/core/src/requests/AssetGraphRequestRust.js
packages/core/graph/src/Graph.js

This change takes 4-5 seconds off `getAssetGraph` by initialising the Graph with the actual edge capacity, removing the need to resize the array multiple times.

Remove resizing overhead by passing edge capacity in getAssetGraph

---

crates/atlaspack/src/requests/asset_graph_request.rs
crates/atlaspack/src/requests/asset_request.rs
crates/atlaspack_core/src/lib.rs
crates/atlaspack_core/src/project_path.rs
crates/atlaspack_core/src/types/asset.rs
packages/core/core/src/requests/AssetGraphRequestRust.js

Once the rust based asset graph is returned, adding all the nodes to the JavaScript based asset graph is quite slow. These changes reduce the amount of fields that are changed to what is necessary. Both the three-js benchmarks and an internal product build show a ~45-65% improvement on the `getAssetGraph` function with these changes.
| Benchmark  | Before | After | Improvement
| - | - | - | - |
| internal | 11.40s | 4.09s | -7.31s (64.14%) |
| three-js | 1.28s  | 0.68s  | -0.6s (46.88%) |
* Mutate asset and dependency values
* Only change what is needed

V3: Simplify asset and dependency processing

---

packages/utils/node-resolver-rs/src/lib.rs
packages/utils/node-resolver-rs/src/tsconfig.rs

- Using `Arc<RwLock>>` for properties in `TsConfig` and `TsConfigWrapper` to avoid cloning the underlying data

Rust: Using smart pointers in resolver to avoid cloning tsconfig

---

packages/core/types-internal/src/index.js

Most of our products want the bundles produced by a `manualSharedBundles` config to have the same name as specified in the config object.
We can do this easily with a namer, but the type has never been added to the public `Bundle` type, despite being actually implemented.
To avoid littering our products with `// @ts-expect-error` calls, adding it to the public types here.

Add manualSharedBundle to the types for Bundle

---

crates/atlaspack_filesystem/src/lib.rs
crates/atlaspack_shared_map/src/lib.rs
packages/utils/node-resolver-rs/src/cache.rs

While doing some performance testing I found that the threadlocal version of the resolver cache was have a large negative impact on build times. Reverting back to the RwLock version is almost halving the asset graph build times in native builds. I have also validated that V2 builds are also performing better with this change, however not by the same margin. 
- Migrate back to RwLock Hash maps for the resolver cache

Update shared hashmap to use RwLock instead of threadlocal

---

crates/atlaspack/src/requests/asset_graph_request.rs
crates/atlaspack/src/requests/entry_request.rs
crates/atlaspack/src/requests/target_request.rs
crates/atlaspack_monitoring/src/tracer.rs
crates/node-bindings/src/atlaspack/atlaspack.rs
packages/core/integration-tests/test/javascript.js

This PR starts the work to enable build tracing in atlaspack. Currently we just want high level function traces.
Running a build with `ATLASPACK_TRACING_MODE=stdout RUST_LOG="info,swc_common=info,swc_ecma_compat_es2015=info,html5ever=info"` gives output of the following format:
```
2024-11-14T06:07:06.410921Z  INFO new: swc_ecma_compat_es2022::class_properties::private_field: close time.busy=4.00µs time.idle=10.9µs
2024-11-14T06:07:06.413204Z  INFO emit_module: swc_ecma_codegen: close time.busy=393µs time.idle=3.08µs
2024-11-14T06:07:06.682738Z  INFO new: swc_ecma_compat_es2022::class_properties::private_field: close time.busy=5.00µs time.idle=7.92µs
2024-11-14T06:07:06.683083Z  INFO emit_module: swc_ecma_codegen: close time.busy=45.9µs time.idle=3.21µs
2024-11-14T06:07:06.695358Z  INFO …
```

add high level trace logs to v3

---

packages/core/core/src/public/BundleGraph.js
packages/dev/eslint-config/index.js
packages/dev/eslint-plugin/index.js
packages/dev/eslint-plugin/package.json
packages/dev/eslint-plugin/src/rules/no-relative-import.js
packages/dev/eslint-plugin/test/rules/no-relative-import.test.js
packages/reporters/conditional-manifest/src/ConditionalManifestReporter.js
packages/reporters/conditional-manifest/src/Config.js
packages/reporters/conditional-manifest/test/ConditionalManifestReporter.test.js
packages/reporters/conditional-manifest/test/Config.test.js

Add a configuration option to `package.json` so we can configure the path for the manifest. This is important as jira needs a separate directory for non-hashed file paths.
- Add filename option to package.json
- Added new eslint package based on eslint-plugin-monorepo which fixes the auto-fixer behaviour

Add manifest path support to conditional reporter

---

crates/atlaspack_core/src/asset_graph.rs
crates/node-bindings/src/atlaspack/atlaspack.rs
packages/core/cli/src/makeDebugCommand.js
packages/core/core/src/Atlaspack.js
packages/core/core/src/requests/AssetGraphRequestRust.js

Serialising the asset graph from Rust to JavaScript can take a significant amount of time for large asset graphs. The current version of Napi is not designed to transport large data structures all at once, which has been alluded to in napi-rs issues in the past.
These changes improve the total time it takes to build the asset graph by serialising with json and parsing the result on the other end, as seen in the following table:
| Benchmark  | Before | After | Improvement
| - | - | - | - |
| internal | 265s | 156s | -109s (41%) |
| three-js | 6.29s  | 4.69s  | -1.6s (25%) |
Whilst serialising to json is not ideal, it can be removed once more of the core has been ported to Rust.
* Improve debug asset graph command logs by specifying an origin and the final build time
* Add `edges` and …

Serialise asset graph as json

---

packages/core/integration-tests/test/api.js
packages/core/integration-tests/test/atlaspack-link.js
packages/core/integration-tests/test/bundle-text.js
packages/core/integration-tests/test/bundler.js
packages/core/integration-tests/test/conditional-bundling.js
packages/core/integration-tests/test/contentHashing.js
packages/core/integration-tests/test/css.js
packages/core/integration-tests/test/encodedURI.js
packages/core/integration-tests/test/globals.js
packages/core/integration-tests/test/glsl.js
packages/core/integration-tests/test/graphql.js
packages/core/integration-tests/test/image.js
packages/core/integration-tests/test/inline-requires.js
packages/core/integration-tests/test/javascript.js
packages/core/integration-tests/test/packager.js
packages/core/integration-tests/test/plugin.js
packages/core/integration-tests/test/scope-hoisting.js
packages/core/integration-tests/test/transpilation.js
packages/core/integration-tests/test/typescript.js
packages/core/test-utils/src/utils.js

Several tests from v3 are now passing, so they have been enabled
* Enable 120 more tests overall (682 → 802, ~51% total tests)
* Fix version handling for `describe` blocks
* Group some related tests together in describe blocks, so they can be disabled all at once

Enable more v3 tests

---

crates/atlaspack_plugin_resolver/src/atlaspack_resolver.rs
packages/utils/node-resolver-core/.gitignore
packages/utils/node-resolver-core/test/fixture/node_modules/graphql/package.json
packages/utils/node-resolver-rs/src/lib.rs

The 'graphql' package contains both '.js' and '.mjs' versions of all it's files. When importing 'graphql' and targetting ESM then you should resolve the '.mjs' version. However, as the package doesn't have an exports key, when importing subpaths like 'graphql/error' you will resolve the '.js' version. This can cause issues as you end up with mismatched constructors.
This PR adds a feature that can attempt to upgrade any '.js' imports in the 'graphql' package to '.mjs' to avoid this issue.

Add graphql ESM upgrade fix to resolver

---

packages/core/core/src/atlaspack-v3/worker/compat/asset-symbols.js
packages/core/core/src/requests/AssetGraphRequestRust.js
packages/transformers/js/core/src/hoist.rs

Some symbols are not passed through to JS and back to Rust correctly, which causes the scope hoisting packager to fail when `isEsm` is not set but `has_cjs_exports` is.
Fix the worker layer to forward through the missing symbols, add tests related to exports introduced while debugging

V3: Forward missing symbols meta

---

packages/core/core/src/atlaspack-v3/worker/compat/environment.js

The environment context in the compatibility layer has been hardcoded to the browser
This modifies the environment to check the context in the `is` environment checks

V3: Fix environment checks

---

packages/core/core/src/Atlaspack.js
packages/core/core/src/atlaspack-v3/WorkerPool.js
packages/core/core/test/atlaspack-v3/WorkerPool.test.js

When running the integration tests, it becomes apparent that we do not cleanup some event listeners and hit the max limit. This may be the cause of the flakey tests we have seen lately, as these changes have had three consecutive green builds without any need to rerun failed tests.
Fix the cleanup of exit and worker listeners

Fix leaky event listeners

---

package.json
packages/bundlers/default/src/bundlerConfig.js
packages/bundlers/default/src/decorateLegacyGraph.js
packages/bundlers/default/src/idealGraph.js
packages/core/core/src/BundleGraph.js
packages/core/core/src/public/BundleGraph.js
packages/core/core/src/public/MutableBundleGraph.js
packages/core/core/src/requests/BundleGraphRequest.js
packages/core/integration-tests/test/conditional-bundling.js
packages/core/types-internal/src/index.js
packages/core/utils/src/collection.js
packages/core/utils/src/index.js
packages/core/utils/test/collection.test.js
packages/packagers/html/src/HTMLPackager.js
packages/packagers/svg/src/SVGPackager.js
packages/reporters/conditional-manifest/src/ConditionalManifestReporter.js
yarn.lock

Currently, in Jira, we have to find every way we serve HTML and make sure we send the conditional bundles for the initial page load. This is difficult as there are many legacy server routes we need to support. To avoid explicitly doing this, we can load all the required bundles in the page load as a fallback and remove these explicit inclusions in some cases.
- Rename symmetric set difference and add set difference function
- Add conditional bundle edges to the bundle graph
- In HTMLPackager, when enabled, insert conditional bundle modules

Add evaluateRootConditionalBundles option so servers can fallback to safe behaviour

---

crates/atlaspack/src/requests/asset_request.rs
crates/atlaspack/src/requests/target_request.rs
crates/atlaspack_core/src/types/asset.rs
crates/atlaspack_core/src/types/environment/engines.rs
crates/atlaspack_plugin_transformer_js/src/js_transformer.rs
crates/atlaspack_plugin_transformer_js/src/js_transformer/conversion.rs
packages/core/core/src/atlaspack-v3/worker/worker.js
packages/core/core/src/requests/AssetGraphRequestRust.js
packages/core/integration-tests/test/css.js
packages/optimizers/css/package.json
packages/packagers/css/package.json
packages/transformers/css/package.json
yarn.lock

This PR makes a couple of changes to ensure that Asset ids are the same as in V2 builds. The primary reason for the difference being that V2 updates the Asset id whenever the file type is updated.   
This PR also fixes an issue where pipelines would be executed correctly on assets that changed file type. 
- Add  `update_id` method to Asset
- Add `set_meta_id` method to Asset
- Update the Asset id whenever a file_type change is detected in the Asset request
- Set the `Asset.meta.id` before the id updates as the packager expects
- Return an undefined query from the node transformers when the query is empty
- Update the default browserslist to match V2
- Ensure Assets run through a new pipeline if they change file type
- Only read the .browserslistrc when it is present. This removes a bunch …

[V3] Ensure Asset ids are in sync with V2 / Fix changing filetype pipelines

---

crates/atlaspack/src/atlaspack.rs
crates/atlaspack_core/src/types/asset.rs
crates/atlaspack_plugin_rpc/src/nodejs/plugins/nodejs_rpc_transformer.rs
packages/core/core/src/CommittedAsset.js
packages/core/core/src/atlaspack-v3/worker/compat/mutable-asset.js
packages/core/core/src/atlaspack-v3/worker/worker.js
packages/core/core/src/requests/AssetGraphRequestRust.js
packages/core/integration-tests/test/sourcemaps.js

Currently v3 does not support sourcemaps in JavaScript plugins, these changes update the workflow to support this feature. It has been found that one soucemap matches v2 internally, but the remaining are difficult to discern with all the bundle output differences in v3.
* Skip serialising the map to JavaScript and commit it to LMDB instead
* Set map key so that the map can be retrieved via LMDB
* Pass map into JavaScript plugin worker and store the result back in Rust
* Add implementations for the JavaScript plugin `getMap` and `setMap`
* Ensure `generate` sets the map if provided in the result (this is what babel relies on)
* Update `CommittedAsset` map buffer handling to account for differences with v3 maps
* Enable v3 sourcemap tests

V3: Support sourcemaps in JavaScript plugins

---

packages/core/integration-tests/test/AtlaspackDevDepRequestBug.test.js

Some flakey integration test failures point to the `overlayFS` and `AtlaspackDevDepRequestBug.test.js` test specifically. One possible cause of files not existing yet is because the fixture is not awaited.
Await the fs fixture

Await fsFixture

---

packages/core/integration-tests/test/workers.js

CI integration tests are fairly flaky and often fail due to the following error:
> should support workers pointing to themselves:
>   Error: done() called multiple times in test <atlaspack should support workers pointing to themselves> in addition, done() received error: Error: ENOENT: no such file or directory, realpath
These changes update the tests so that the flakiness no longer occurs, it has been reproduced and verified locally via stress testing

Fix flaky worker tests

---

crates/atlaspack/src/requests/asset_request.rs
crates/atlaspack_core/src/types/asset.rs
crates/atlaspack_plugin_transformer_css/src/css_transformer.rs
crates/atlaspack_plugin_transformer_js/src/js_transformer.rs
crates/atlaspack_plugin_transformer_js/src/js_transformer/conversion.rs
packages/core/integration-tests/test/atlaspack-v3.js

This PR attempts to make the V3 output more closely match the V2 one. I have added some tests that build apps with both versions and assert their output is identical. I have also made a few changes to ensure the tests are passing. 
- Add tests for ensuring V2 and V3 output are identical
- Change CSS module quote style to match V2
- Only use virtual code in ID generation when it comes from the resolver (matches V2 behaviour)
- Replicate V2 environment for `esmodule-helpers` import

[V3] Make V3 output closer to V2

---

.mocharc.js
.mocharc.json

This allows us to run:
```
yarn mocha ./...
```
To run a subset of tests.

Update with mocha js configuration

---

crates/atlaspack_monitoring/src/tracer.rs
crates/node-bindings/src/js_tracing.rs
crates/node-bindings/src/lib.rs
packages/core/core/src/Atlaspack.js
packages/core/core/src/SymbolPropagation.js
packages/core/core/src/requests/AssetGraphRequestRust.js
packages/core/core/src/tracer.js
packages/core/integration-tests/test/bundler.js
packages/core/rust/index.js.flow

This commit adds a way to instrument javascript code with the rust tracing implementation.
This allows unified chrome profiles to be generated that include both rust and javascript spans.
Since span names need to be static, currently javascript spans will need to be labeled with a `label` arg/attribute.

Expose rust tracing instrumentation to javascript

---

packages/core/core/src/BundleGraph.js
packages/core/graph/src/AdjacencyList.js
packages/core/graph/src/Graph.js
packages/core/graph/test/AdjacencyList.test.js

Prevents creating temporary arrays when finding the asset linked to a dependency. This is a relatively hot path in the bundler and can improve its performance.
I will perform a dev release from this branch and do some performance testing.

Modify BundleGraph::getAssetWithDependency to use graph iteration methods

---

crates/atlaspack/src/error.rs
crates/atlaspack/src/lib.rs
crates/atlaspack/src/request_tracker/request_tracker.rs
crates/atlaspack_core/src/types/diagnostic.rs
crates/node-bindings/src/atlaspack/atlaspack.rs
crates/node-bindings/src/atlaspack/mod.rs
crates/node-bindings/src/atlaspack/napi_result.rs
packages/core/core/src/atlaspack-v3/AtlaspackV3.js
packages/core/core/src/requests/AssetGraphRequestRust.js

Errors are currently sent to the JavaScript layer as strings. This is a problem because the JavaScript layer currently handles formatting the error output from a `Diagnostic` object - which cannot be done from a string leading to poor error messages.
This PR allows Rust to return `Diagnostic` objects to JavaScript to handle formatting and printing. This works by having Rust check if the internal `anyhow::Error` is a `Diagnostic`, if it is then it converts it to JavaScript and returns that otherwise it returns the error in string form.
On the Napi side, to serialize the `Diagnostic` value we need access to `Env` which isn't available in `deferred.reject()` so instead the error value is passed via `deferred.resolve()`. 
This then necessitated `AtlaspackNapi.buildAssetGraph()` returning a …

V3: Passing diagnostics from Rust

---

packages/core/integration-tests/test/inline-requires.js
packages/optimizers/inline-requires/src/InlineRequires.js

The wrong source-map was getting returned from inline requires.
An integration test is added to verify the mapping is correct (and was failing previously with the inline requires optimizer, but not with only the transformer).

Fix inline requires source map generation

---

packages/core/integration-tests/test/inline-requires.js

The inline require sourcemaps test specifies the js transformer when it does not need to, since it is already part of the default config. Although this reveals a difference between how v2 / v3 processes config, it's usually expected you specify the full `*.{js,mjs,jsm,jsx,es6,cjs,ts,tsx}` transformer glob when overriding js transformers to avoid issues.
Remove js transformer from test fixture

Fix inline require sourcemaps test

---

packages/reporters/conditional-manifest/src/ConditionalManifestReporter.js

Thanks @MonicaOlejniczak for figuring this one out!
Turns out in CI that we have a race condition for creating the manifest. While we'd expect the fragment directory has already been created, this seems to not be guaranteed in CI.
Make sure the directory exists before writing to it

Mitigate missing dir race condition in conditional manifest reporter

---

packages/core/core/src/requests/AssetGraphRequestRust.js
packages/core/core/test/requests/AssetGraphRequestRust.test.js
packages/core/integration-tests/test/atlaspack-v3.js

In cases where an Assets type changed and therefore it's id, the Dependency.sourceAssetId property can become out of sync with the Asset. This causes an issue where some dependencies are missing when using `Asset.getDependenices()` in a reporter. 
This PR changes dependencies to instead use the edge data as the point of truth when mapping `Asset.dependencies` in `getAssetGraph`.

[V3] Fix Asset.dependencies mapping

---

packages/core/core/src/RequestTracker.js

We use these events to time the cache write, however currently they only are reported after doing some serialization work and clean-up.
This moves the reporting to the top of the procedure.

Report cache write start at the start of the write

---

benchmarks/three-js/scripts/build.mjs
packages/core/core/src/atlaspack-v3/AtlaspackV3.js

Ensure worker shutdown after asset graph is built. This will hopefully stop the potential build hanging we've been seeing.

[V3] Ensure worker shutdown after asset graph is built

---

.github/workflows/ci.yml

We've seen some issues lately where integration tests are hanging for extended periods of times, hogging the agents in the pool. We've also been getting queued by running tests on stale commits when PRs are being pushed to actively.
- Add a concurrency group so stale commits still being built will be cancelled when a newer commit is pushed
- Add a timeout (35 mins) to integration tests to ensure they don't run for extended periods if they hang

Cancel stale CI builds and add CI timeout

---

packages/core/cache/test/LMDBLiteCache.test.js
packages/core/codeframe/test/codeframe.test.js
packages/core/core/src/Dependency.js
packages/core/core/test/Dependency.test.js
packages/core/core/test/requests/AssetGraphRequestRust.test.js
packages/core/integration-tests/test/bundle-text.js

Working towards fixing the flakey integration tests. This PR adds type checking to some tests that are missing types.
**Notes:** 
Type checking only occurs on test files that are annotated with `// @flow` however this is not enforced and files not annotated can still be written with flow and will still have their types stripped by babel register. 
This leads to misleading usage of APIs and related problems.
Currently, many of the tests that are not type checked are actually using incorrect type signatures to call Atlaspack APIs making it difficult to refactor the tests to improve their reliability.
In future I will enable type checking enforcement on tests, this will help with tracing the cause of brittle tests and also help with the eventual migration to TypeScript

Reliability: Flow types for tests

---

packages/core/integration-tests/test/BundleGraph.js
packages/core/integration-tests/test/bundle-text.js
packages/core/integration-tests/test/bundler.js
packages/core/integration-tests/test/cache.js
packages/core/integration-tests/test/css.js
packages/core/integration-tests/test/glob.js
packages/core/integration-tests/test/html.js
packages/core/integration-tests/test/incremental-bundling.js
packages/core/integration-tests/test/javascript.js
packages/core/integration-tests/test/lazy-compile.js
packages/core/integration-tests/test/rust.js
packages/core/integration-tests/test/scope-hoisting.js
packages/core/integration-tests/test/server.js
packages/core/integration-tests/test/svg.js
packages/core/integration-tests/test/typescript.js
packages/core/integration-tests/test/wasm.js
packages/core/integration-tests/test/watcher.js
packages/core/integration-tests/test/webextension.js
packages/core/integration-tests/test/workers.js
packages/core/integration-tests/test/worklets.js
packages/core/test-utils/src/utils.js
packages/runtimes/js/src/JSRuntime.js
packages/runtimes/js/src/helpers/bundle-url-common.ts
packages/runtimes/js/src/helpers/bundle-url-shards.ts
packages/runtimes/js/src/helpers/bundle-url.js
packages/runtimes/js/src/helpers/bundle-url.ts
packages/runtimes/js/test/bundle-url-common.test.js
packages/runtimes/js/test/bundle-url-shards.test.js

In order to support domain sharding for HTTP1.1 users, we need to apply shards in two places. Firstly, in the generated HTML, which is done at request time by the SSR server (as we need to know whether this is a 1.1 request or not). Secondly, when requesting bundles from within other bundles we need to shard those requests as well, and not just rely on the parent shard.
To support this, I've made some changes to the JS Runtime, adding in a sharded version of `helpers/bundle-url` which is activated if the domain sharding config is provided in a build.
```json
"@atlaspack/runtime-js": {
"domainSharding": {
"maxShards": 5,
"cookieName": "should.shard.domains"
}
}
```
`bundle-url-shards` started out as a copy of `bundle-url`, but has been refactored a bit to make the more complicated logic …

Add domain sharding to js runtime

---

gulpfile.js

When adding [domain sharding][ds], I migrated the bundle-url files to TypeScript so I would know what was going on in them.
Unfortunately this causes them to be skipped by the babel step in the gulpfile, which is [only looking for `*.js`][glob].
Adding TS into the babel compile step turned out to be a massive headache, so I've just added them to the copyOthers step.
When getting renamed later in the file, they depend on `vinyl.base` being `packages/`, so I've had to add some kind of glob syntax in that second path segment.
[glob]: https://github.com/atlassian-labs/atlaspack/blob/fix-missing-ts-files/gulpfile.js#L27
[ds]: https://github.com/atlassian-labs/atlaspack/pull/268

Copy new TypeScript files to lib

---

packages/runtimes/js/src/JSRuntime.js
packages/runtimes/js/src/helpers/bundle-url-shards.ts
packages/runtimes/js/test/bundle-url-shards.test.js

Originally domain sharding was set up to work by looking for the presence of some specified cookie to decide whether to shard or not, as this is what the CFE SSR server does already.
However that's a little less easy to use, and other products would prefer to use a key on the `window` object instead.
Now, the runtime looks for a boolean value in `window.__ATLASPACK_ENABLE_DOMAIN_SHARDS` as its switch.
SSR servers can inject an inline script tag at the top of the document if sharding is required.
```html
<script>
window.__ATLASPACK_ENABLE_DOMAIN_SHARDS = true;
</script>
```
Or, if cookie based logic is still preferred
```html
<script>
window.__ATLASPACK_ENABLE_DOMAIN_SHARDS = document.cookie.indexOf('existing.cookie.name') !== -1;
</script>
```

Switch to using a global property for domain sharding

---

packages/utils/domain-sharding/package.json

My package.json was probably a little bit minimal. Lerna is failing to publish, so taking some config from another package that seems to be required

Add publish config for new domain sharding package

---

.mocharc.js
package.json
packages/core/core/package.json
packages/core/integration-tests/package.json
packages/core/integration-tests/test/bundler.js
packages/core/integration-tests/test/cache.js
packages/core/integration-tests/test/library-bundler.js
packages/core/integration-tests/test/macros.js
packages/core/logger/package.json
packages/core/workers/package.json
packages/core/workers/test/integration/workerfarm/console.js
packages/core/workers/test/integration/workerfarm/ipc-pid.js
packages/core/workers/test/integration/workerfarm/ipc.js
packages/core/workers/test/integration/workerfarm/logging.js
packages/core/workers/test/workerfarm.test.cjs
packages/dev/babel-register/index.js
packages/dev/babel-register/package.json
packages/dev/eslint-config/index.js

This PR verifies that tests are using the correct transpiler/type checker for the file type and adds support for tests written in TypeScript
Rules:
|Condition|Engine|
|-|-|
|`.js` `.cjs` `.mjs` | node native |
|`.js` `.jsx` `startsWith('// @flow')` | babel register |
|`.ts` `.mts` `.cts`  | esbuild register |
There were many test files that were being type stripped as Flow files implicitly without being type checked because the files were not annotated with `// @flow`. Some TypeScript files were actually being stripped by Flow and were working because they only used syntax that overlapped.
This allowed tests to be written with invalid JavaScript syntax and invalid Flow types causing subtle drift from core APIs. This resulted in the accumulation of skipped tests that could no longer be run …

WIP Reliability: Enforce type checking on tests

---

packages/core/integration-tests/test/domain-sharding.js
packages/core/test-utils/src/utils.js
packages/runtimes/js/src/JSRuntime.js
packages/runtimes/js/src/helpers/browser/esm-js-loader-shards.js

Seems there was another code path I was not aware of that can generate URLs that needs to be sharded.
When outputting to ESM, the runtime imports `esm-js-loader` and calls its load function with the public ID we're after.
To avoid things becoming entirely too messy, I've created a new `esm-js-loader-shards` that will call the sharding helper on the URL generated, before passing it to `import`.
Adding a test for this required updating the `run` integration test helper so that it could handle sharded domains (because it was trying to request assets from `integration/dist-4/a.hash.js`).

Fix domain sharding for ESM output

---

packages/utils/domain-sharding/package.json
yarn.lock

Bit annoying to use the package when it has no types. TypeScript is capable of rendering JSDoc to a `.d.ts` file by itself, so no need for the Flow converter.

Publish TS types with domain sharding package

---

packages/core/integration-tests/.mocharc.json

Adding config to allow integration tests to see TypeScript files

Rel: TypeScript support in integration tests

---

packages/runtimes/js/src/JSRuntime.js

I'm not sure why ESLint isn't capable of catching this, even in the playground online it won't trigger. But the sharding setup doesn't need this anymore, so it can be removed from `getAbsoluteUrlExpr`

Remove unused reference in JSRuntime

---

packages/core/core/src/requests/BundleGraphRequest.js
packages/core/core/src/requests/asset-graph-dot.js

Trying to debug determinism bugs in v3, wrote a little renderer that converts the AssetGraph into GraphViz dot format.
```bash
export DEBUG_ASSET_GRAPH_DOT="./asset_graph.dot" 
#optional 
export DEBUG_ASSET_GRAPH_DOT_STYLE="true" 
export DEBUG_ASSET_GRAPH_DOT_SORT="true" 
npx atlaspack build
cat ./asset_graph.dot
```

Optionally render AssetGraph to GraphViz dot format

---

packages/utils/node-resolver-rs/src/package_json.rs

Unfortunately, this [ecosystem pollution][pol] has spread to our world as well, and we've inherited Parcel's problem of not parsing the main field as a boolean.
This PR just replicates [Devon's patch][p] into Atlaspack, including his test.
[p]: https://github.com/parcel-bundler/parcel/pull/10053/commits/bb97f0e68e113bf31c7d35f95b385fa33b0c4d20
[pol]: https://github.com/es-shims/dunder-proto/issues/2

Replicate the `"main": false` patch from Parcel

---

.github/actions/rust-toolchain/action.yml
.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/repl.yml

Bumping the rust version in this repository is tedious, because each job needs to specify the toolchain version. Other rust actions are either archived, do not provide enough features or good defaults.
Create a centralised local action that reads from the rust toolchain file, so that we only need to change the version in one place. This has the benefit of not needing to define dependent jobs in multiple workflows.
Note that `actions-rs/toolchain@v1` was replaced as well, and that the default profile in `dtolnay/rust-toolchain@master` is also `minimal` so it should not cause any issues.

Use rust toolchain version in workflows

---

packages/runtimes/js/src/helpers/browser/esm-js-loader-retry.js

The previous import retry feature gave the consumer the ability to retry failed requests. This required the consumer to handle the actual retry logic:
```javascript
for (let i = 0; i < 5; i++) {
try {
await import('./foo')
} catch(err) {
await new Promise(res => setTimeout(res, 1000))
}
}
```
This PR added the retry logic into the JavaScript runtime, enabled with `--feature-flag importRetry=true`
```javascript
await import('./foo') // will auto retry on failure
```
For reporting purposes, it will also emit a custom event on the window to notify when retries were triggered
```javascript
window.addEventListener('atlaspack:import_retry', ({detail}) => console.log(detail));
```

Added import retries into packager

---

packages/core/package-manager/src/NodePackageManager.js
packages/core/package-manager/src/nodejsConditions.js

This PR allows the bundler to select plugins and internals using Nodejs's [conditional exports](https://nodejs.org/api/packages.html#conditional-exports)
This will help with the migration path to TypeScript as it allows us to select sources using built-in Nodejs conditional resolution (and builtin nodejs TypeScript support)
```bash
NODE_OPTIONS="--condition=@atlaspack::sources" atlaspack build
node --condition=@atlaspack::sources ./node_modules/.bin/atlaspack build
```
Where Atlaspack packages will be ported to
```json
{
"name": "@atlaspack/foo",
"exports": {
"@atlaspack::sources": "./src/index.ts",
"types": "./src/index.ts",
"default": "./lib/index.js",
}
}
```

Dev: Enable the use of "exports" when resolving bundler plugins

---

packages/runtimes/js/src/helpers/browser/esm-js-loader-retry.js

Expanded the import retries logic to include a global cache to avoid issues when multiple imports for the same asset occur simultaneously. Example:
```javascript
Promise.all([
import('./foo'),
import('./foo'),
])
```

Fix: Import retries - simultaneous imports

---

packages/core/integration-tests/test/scope-hoisting.js
packages/packagers/js/src/ScopeHoistingPackager.js

From the issue found by @alshdavid. simple fix to avoid errors and deoptimise if the bundle doesn't support symbols.
When a dependency doesn't have symbols, don't error but just deoptimise instead.

Fix unused symbols for dependencies without symbols

---

CONTRIBUTING.md

Add a very basic list of commands to build Atlaspack locally.
I could not set up Atlaspack locally, and I wish I knew to run these commands.
Extend `CONTRIBUTING.md` to include a list of commands to build Atlaspack locally and get to the point where one can run the examples.
I also fixed a stray comment.

Add basic commands to set up atlaspack

---

packages/utils/domain-sharding/src/index.js
packages/utils/domain-sharding/test/index.test.js

To improve CHR with domain sharding when switching between HTTP 1 and 2, use the base domain as a possible domain when sharding URLs.
For example, a config with `maxShards: 4` and a public path of `http://atlaspack-assets.com`would result in the following possible domain shards.
```
http://atlaspack-assets.com // <-- Include the base domain on top of the 4 sharded domains
http://atlaspack-assets-0.com
http://atlaspack-assets-1.com
http://atlaspack-assets-2.com
http://atlaspack-assets-3.com
```

Add base domain to domain sharding possibilities

---

.github/workflows/release.yml

It's difficult to know what commit is in Canary releases, so I hacked this together quickly.
I'm not very familiar with how to write proper actions here, so I just use the NPM CLI and GitHub script API to add the tag. Any suggestions on how to make this a bit cleaner would be welcome

Add canary tag to each release commit

---

packages/core/cache/index.d.ts

They weren't exposed previously.
Test Plan: N/A

Fix LMDBLiteCache typescript bindings

---

packages/core/graph/src/ContentGraph.js
packages/core/graph/test/ContentGraph.test.js

Adds a method to retrieve content keys associated with node IDs.
Test Plan: Run unit-tests (yarn test)

Add ContentGraph::getContentKeyByNodeId

---

flow-typed/npm/sinon_v7.x.x.js

Fixes flow type bindings so that further refinement assertions can be built
with typechecking.
For example, this is currently failing to typecheck:
```
const writeFileSync = sinon.stub(fs, 'writeFileSync');
const count = writeFileSync.withArgs('f', 'contents').callCount;
```
And will typecheck now.
Test Plan: `yarn flow`

Fix sinon flow bindings

---

packages/bundlers/bundler-experimental/src/DominatorBundler/cycleBreaker/findStronglyConnectedComponents.js
packages/bundlers/bundler-experimental/test/DominatorBundler/cycleBreaker/findStronglyConnectedComponents.js

Adds an implementation of Tarjan's algorithm to find strongly connected
components.
This will be used on the experimental bundler to simplify cycle handling and
can be used on other parts of the codebase to simplify the symbol propagation
implementation.
On the bundler, we will use this to convert the graph to an acyclic graph
(replace the strongly connected components with a single 'group' node) before
doing other work.
Test Plan: yarn test

Add Tarjan SCC algorithm implementation

---

Cargo.lock
crates/atlaspack_vcs/Cargo.toml
crates/atlaspack_vcs/src/lib.rs

Improves performance of listing yarn lock files and VCS changes by:
* changing exclude patterns
* using rayon
Test Plan: cargo test

Improve performance of VCS diff listing

---

.changeset/tall-impalas-suffer.md
packages/core/logger/src/tracer.js

The tracer wasn't ending these async function spans properly.
This is of limited use at the moment because async functions might overlap, so
the spans won't be quite right as is.
Test Plan: N/A

Fix exiting async function spans

---

.changeset/mighty-zoos-design.md
crates/atlaspack_vcs/src/lib.rs
packages/core/rust/index.js.flow

Tested locally by running `cargo run --example vcs_file_diff snapshot --repository-root="../../"`

Add tracing logs around git dirty hashes listing

---

crates/atlaspack_vcs/examples/vcs_file_diff.rs
crates/atlaspack_vcs/src/lib.rs
crates/node-bindings/src/vcs.rs
packages/core/fs/src/NodeVCSAwareFS.js
packages/core/rust/index.js.flow

Adds support for VCS change lists to differentiate between create/delete/update
events.
Test Plan: cargo test

Support specific event types from vcs fs

---

.changeset/honest-wombats-pay.md
crates/atlaspack_vcs/src/lib.rs
crates/atlaspack_vcs/src/yarn_integration/mod.rs
packages/core/fs/src/NodeVCSAwareFS.js

If a lock-file is added into the repository then we will consider all
dependency paths changed.
Test Plan: cargo build

Fix case where lockfiles are added into a repo

---

crates/atlaspack_vcs/src/lib.rs

Fix VCS events since listing to include currently untracked files.
Test Plan: cargo test

Fix initial change listing with statuses

---

.changeset/many-pears-tan.md
.changeset/popular-coins-complain.md
packages/core/core/src/requests/AssetGraphRequest.js
packages/core/core/src/requests/BundleGraphRequest.js
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js
packages/core/integration-tests/test/loadable.js

Confluence is having an issue adopting the inline requires optimizer because the way Loadable is set up puts a lot of side effects throughout the codebase, and inlining the requires messes that up.
This can be made to work by setting a large number of `package.json`s to have `"sideEffects": true`, but that can easily be ruined by someone incorrectly configuring another package.
A more robust approach is to find any imports of `@confluence/loadable`, and follow the asset graph up to mark all ancestor as having side effects. This ensures that transitive deps will be marked also.
Functionality is locked behind a feature flag.

Add a step for scanning for side effects caused by loadable package

---

.changeset/shaggy-balloons-hide.md
crates/atlaspack_core/src/types/feature_flags.rs
packages/core/core/src/atlaspack-v3/AtlaspackV3.js
packages/core/integration-tests/test/atlaspack-v3.js
packages/core/rust/index.js.flow

Feature flags can also be string values, updating V3 to account for that

V3: String or bool feature flag

---

crates/atlaspack/src/atlaspack.rs

Moving `AtlaspackState` and `RequestTracker` to top level of `Atlaspack` to facilitate persistent state in watch mode

V3: Moving RequestTracker to top level of Atlaspack

---

.changeset/metal-games-tell.md
Cargo.lock
crates/atlaspack_plugin_optimizer_inline_requires/Cargo.toml
crates/atlaspack_plugin_optimizer_inline_requires/src/lib.rs

We've recently had a bug reported with the inline requires optimizer, that was causing variables to not be defined.
As an example:
```js
parcelRegister("k4tEj", function(module, exports) {
Object.defineProperty(module.exports, "InternSet", {
enumerable: true,
get: function() {
return $g34Jm.InternSet;
}
});
// Approx 500 lines of separation...
var $g34Jm = require("internmap");
});
```
Because the inline requires optimizer replaces as it goes, it can't start inlining requires until it's encountered the first instance of each one in the file. This means that instances of `$g34Jm` below the require of internmap were being inlined, but the ones above were not.
To fix this, we've refactored the inline requires optimizer to work as a two-pass system. First, we run a "collector" visitor over …

Update the inline requires optimizer to fix ordering bug

---

.changeset/hip-deers-occur.md
packages/utils/babel-plugin-transform-contextual-imports/package.json
packages/utils/babel-plugin-transform-contextual-imports/src/index.ts
packages/utils/babel-plugin-transform-contextual-imports/test/babel-plugin-transform-contextual-imports.test.js
yarn.lock

For supporting importCond with jest APIs, it's much more trivial to lean on the server style proxying of the import object. This means we can set the feature gate at runtime, allowing for feature gate test suites to work seamlessly in the monorepo. It may make more sense to just support loading fresh modules (more like the browser environment), but it's a big rabbit hole to go down for a small benefit.
This change moves to update each identifier in the module, referencing importCond assignment, to the lazy getter.

Use new server syntax that works in jest env

---

packages/core/core/src/Atlaspack.js

Let's forward watcher errors to monitoring
Test Plan: N/A

Track watcher callback errors

---

.changeset/swift-meals-ring.md
packages/utils/node-resolver-rs/src/lib.rs
packages/utils/node-resolver-rs/src/tsconfig.rs

It seems we are doing a lot of memory allocation on `TsConfig::extends`, which
should be fixed by this diff.
Test Plan: cargo test

Reduce resolver allocations

---

.changeset/tasty-maps-serve.md
packages/utils/node-resolver-core/src/Wrapper.js

Warn if the resolver falls into the JavaScript fs.
Test Plan: yarn test

Add warning when using javascript fs

---

.changeset/warm-eagles-tell.md
packages/bundlers/default/src/idealGraph.js
packages/core/integration-tests/test/bundler.js

This PR resolves an issue with re-used bundles when they have circular dependencies on each other. Previous to this fix, Assets that were required by two async bundles that had a circular dependency on each other would not be placed in either bundle, causing `Cannot find module` errors at runtime.  
The change here ensures that Assets are not removed from reused bundles when there isn't anywhere else safe to put them.

Fix re-used bundles for async imports with circular dependencies

---

.changeset/dirty-mangos-lick.md
packages/transformers/js/core/src/fs.rs
packages/transformers/js/core/src/lib.rs

We have seen some segfaults again that may be related to the fold usages within the transformer. These changes replace `Fold` with `VisitMut` in the `inlineFS` feature of the JS transformer.
Replace `impl Fold` with `impl VisitMut` in `InlineFS` and add new test cases

Remove fold from inlineFs

---

.changeset/great-apricots-suffer.md
packages/transformers/js/core/src/constant_module.rs
packages/transformers/js/core/src/env_replacer.rs
packages/transformers/js/core/src/esm_to_cjs_replacer.rs
packages/transformers/js/core/src/global_replacer.rs
packages/transformers/js/core/src/lib.rs
packages/transformers/js/core/src/node_replacer.rs
packages/transformers/js/core/src/typeof_replacer.rs

Refactor some of the transformer tests to create consistency, and add missing tests to the esm fold
* Rename `modules.rs` to `esm_to_cjs_replacer`
* Rename `ESMFold` to `EsmToCjsReplacer`
* Add unit tests to `EsmToCjsReplacer`
* Remove `esm2cjs` fn in favour of `EsmToCjsReplacer` with the fold logic lifted up, both to enable testing and consistency
* Update some transformer tests to be more consistent

Update transformer tests and rename ESMFold to EsmToCjsReplacer

---

.changeset/shiny-bikes-compete.md
packages/transformers/js/core/src/dependency_collector.rs
packages/transformers/js/core/src/lib.rs

We have seen some segfaults again that may be related to the fold usages within the transformer. These changes replace `Fold` with `VisitMut` in the dependency collector of the JS transformer.
* Replace `impl Fold` with `impl VisitMut` in `dependency_collector`
* Reformat and add new test cases
* Remove unused `rewrite_require_specifier` fn verified via testing, the specifier is always replaced by then so it never does anything in both the old and new code paths
* Make ast imports consistent and remove custom use statements
* Centralise the collector, hygiene, and resolver passes into main block
These changes were tested in Jira, and confirmed to have the same build assets and descriptors.

Replace Fold with VisitMut in the dependency collector

---

.changeset/good-apes-mate.md
packages/transformers/js/core/src/esm_to_cjs_replacer.rs
packages/transformers/js/core/src/lib.rs
packages/transformers/js/core/src/utils.rs

We have seen some segfaults again that may be related to the fold usages within the transformer. These changes replace `Fold` with `VisitMut` in `EsmToCjsReplacer` of the JS transformer.
* Replace `impl Fold` with `impl VisitMut` in `EsmToCjsReplacer`
* Update how the replacer is called to work with visit

Replace Fold with VisitMut in EsmToCjsReplacer

---

package.json
yarn.lock

Fix CI build hangs. 
It looks like the recent V3 + Mac test hangs were caused (or at least hugely worsened) by something in the parcel watcher. Upgrading seems to fix the flakiness we were seeing. 
[no-changeset]: This change only updates deps for the workspace, not consumers

Upgrade @parcel/watcher

---

.changeset/lazy-ligers-argue.md
crates/atlaspack/src/requests.rs
crates/atlaspack/src/requests/target_request.rs
packages/core/integration-tests/test/watcher.js

Prior to this change V3 didn't handle custom `distDir` settings in target descriptors passed straight to the node API.

V3: Fix handling of distDir from target descriptors

---

.changeset/calm-laws-study.md
crates/node-bindings/src/atlaspack/atlaspack.rs
packages/core/core/src/atlaspack-v3/AtlaspackV3.js
packages/core/rust/index.js.flow

I noticed some code was incorrect when investigating build hangs, so these changes fix that
* Fix `respondToFsEvents` return type
* Remove dead `MAX_STRING_LENGTH` constant

Remove dead constant and fix respondToFsEvents types

---

.changeset/good-toes-worry.md
packages/utils/babel-plugin-transform-contextual-imports/src/index.ts
packages/utils/babel-plugin-transform-contextual-imports/test/babel-plugin-transform-contextual-imports.test.js

The recent breaking change shipped to the babel plugin was not within our new process, so if we bring back the original config option - we can bump without config changes
Bring back the original code but behind a function, so it can be easily deleted in a future PR.

Bring back server option to transform-contextual-imports

---

.changeset/gentle-eggs-play.md
crates/lmdb-js-lite/package.json

We don't produce Windows binaries but I sometimes use my Windows desktop to develop Atlaspack. This one line change allows Atlaspack to be built on Windows machines.

Fixing Windows build

---

.changeset/mean-feet-look.md
packages/core/core/src/loadAtlaspackPlugin.js

We were receiving reports of some "unable to resolve" errors since merging #383 where the resolver can't find the plugins required. This is being caused by the fact that when a dependency was listed in `parcelDependencies`, we would set the `resolveFrom` to be the project root and then continue on.
Since `parcelDependencies` no longer exists, it doesn't make sense to special case whether or not this plugin is in the package.json of the default config plugin anymore. This PR removes that check entirely, so it shouldn't throw errors on plugins that aren't explicitly listed anymore (so long as they're in the project's `package.json`).

Remove the vestigial `parcelDependencies` config check 

---

.changeset/slimy-crews-count.md
packages/bundlers/default/src/MonolithicBundler.js
packages/core/integration-tests/test/monolithic-bundler.js

When making the isolated bundles change (#405), I added a check that a dependency should have one and only one asset.
This is of course completely incorrect, because external dependencies have no assets, and things like CSS Modules will have two assets.
The fix here is just to iterate over the assets that are returned and handle each asset individually.

Fix css modules case for single file output

---

.changeset/thirty-fishes-wait.md
crates/atlaspack_vcs/src/lib.rs

Query git status from the CLI rather than libgit2 so we can support sparse checkouts.

Support sparse checkouts

---

.changeset/weak-mails-dream.md
packages/bundlers/default/src/MonolithicBundler.js
packages/core/integration-tests/test/monolithic-bundler.js

The isolated bundles are more complicated than expected, and will probably require the `tesseract` target to be added to be handled properly.
Instead, we're addressing this issue in the product by making images into data urls on the server, which requires that the single file bundler supports inline bundles.
It also doesn't really make sense for the single file output mode to even have isolated bundles, since they can't exist in the output, so we've banned them for now.
This is a very basic one, and just switches the existing behaviour for handling isolated bundles over to inline, and makes isolated bundles an error.

Support inline bundles for single file output

---

.changeset/swift-fishes-shave.md
crates/atlaspack_swc_runner/src/runner.rs
packages/transformers/js/core/src/collect.rs
packages/transformers/js/core/src/hoist.rs
packages/transformers/js/core/src/utils.rs

Most of the collect and hoist tests are inconsistent and miss assertions that were in previous tests
* Move collect tests from hoist into collect
* Refactor tests to use assertion functions that always assert consistent behaviour per suite
* Use test utils in hoist to create consistency
* Update `RunContext` to include `is_module` for hoist tests
* Update test runner to handle comments, matching the original hoist test setup
* Favour functions and new structs over macros

Refactor collect and hoist tests

---

.changeset/fluffy-students-fail.md
packages/core/core/src/Atlaspack.js
packages/core/workers/src/process/ProcessWorker.js
packages/core/workers/src/threads/ThreadsWorker.js

Replace `require.resolve` for known static file paths with `path.join` (workers)
This is unsupported in Nodejs `type: module`, increases the difficulty of migrating to modern Nodejs and prevents the use of Atlaspack with alternative runtimes (experimenting with Deno, Bun, etc)

Chore: Replace require.resolve with path.join for workers

---

.changeset/rude-cats-mate.md
packages/core/core/src/requests/WriteBundlesRequest.js
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js

Change bundles packaged/listed so that inline bundles' source-maps and contents
are written to disk.
Add null check so that inline bundles referencing their parent bundles in the
source-mapping URL still work.
Test Plan: Change is experimental and feature-flagged / subject to change

Fix inline bundle source maps writting

---

.github/workflows/canary-release.yml
.github/workflows/release.yml

In order to get Changesets to actually do our publishing, we need to add it as our release step. For Changesets, this comes in two parts, versioning and publishing. Luckily for us, the Changesets action takes care of both of these.
I've separated the canary and release steps. Once Changesets is all working and confirmed, we'll turn off canaries entirely. For ad hoc branches that need testing, I'll also add Snapshots.
[no-changeset]: Updating github actions

Add changesets action

---

.github/workflows/release.yml
.gitignore

Turns out that because Changesets needs to make commits, and the debug files are not ignored, it ends up trying to accidentally add some monstrous files to the repo.
It was also breaking canary releases, because they were both attempting to upload an artifact with the same name.
To fix this, I've added the artifacts directories to .gitignore, so that Changesets won't try to include them, and taken the debug symbols step out of Changesets for now. We can reintroduce it once canaries are gone.
[no-changeset]: Updating github action

Fix changesets action

---

.changeset/config.json

By default, Changesets will apply a major bump to a package if it needs to update the peer dependencies. Especially in a monorepo environment, this means we can end up with major releases very frequently on even patch changes to other packages in the repo.
The fix here is to enable the Changesets option to only update a peer dependency if the new version of the dependent package is out of range. When using `^` ranges, this means we only bump a major if the dependent package gets a major bump.
I think this should really be Changesets' default behaviour to be honest, and I've always enabled it on previous projects that have used it.
[no-changeset]: Updating changeset config only

Disable peer deps causing majors

---

.changeset/breezy-nails-sip.md
crates/atlaspack_swc_runner/src/runner.rs
packages/core/integration-tests/test/inline-requires.js

This code is used in the inline requires optimizer.
Keeping comments seems to trigger some bug in SWC which produces invalid code.
In particular code such as:
```
255 / /* PURE */ e(...)
```
Ends up being outputted as:
```
255 //* PURE */ e(...)
```
This ends-up producing invalid bundles due to syntax errors.
A change made in #407, added comment support to the inline requires optimizer,
which triggered this bug.
Test Plan: integration tests reproducing the error will be added to this diff

Strip comments on SWC optimizer

---

.changeset/poor-lions-look.md
packages/core/fs/src/NodeVCSAwareFS.js

This adds error handling so that if reading the yarn state files fails the
server will still function.

Add more resilient error handling to NodeVCSAwareFS

---

.changeset/clever-needles-argue.md
crates/atlaspack_vcs/src/lib.rs

Sometimes files are included in git ls-files' output but can't be read.

Be more permissive about yarn.lock files missing

---

.github/workflows/release.yml

Ubuntu 20.04 runners are deprecated.
Test Plan: N/A
[no-changeset]: Change to GitHub actions

Upgrade ubuntu

---

.github/workflows/build-smoke-test-images.yml
docker/multiarch-node/Dockerfile
docker/multiarch-node/README.md

Built on ubuntu 22.04.
We have smoke tests for `armhf` and `arm64` which run on a docker image. This docker image is using an older version of GLIBC, which is incompatible with the version on `22.04`. Ubuntu `20.04` runners aren't working anymore, so the build runners will be upgraded to `22.04`.
This diff will add a build for docker images with Node.js for those architectures, based on ubuntu 22.04. We will then update the smoke test workflow to use these. I need to merge to be able to run the workflow.
Test Plan: N/A
[no-changeset]: Adding docker images for smoke testing

Add multi-arch Node.js docker image

---

scripts/build-native.js

Fixing native build
CI uses a slightly different env var name in the `scripts/build-native.js` script
[no-changeset]: build script

CI: Fix native build

---

packages/core/rust/package.json
scripts/build-native.js

Build script will do a double build for napi projects because `@napi-rs/ci` does some stuff internally that triggers it
- Update native build script to run the `napi build` command from the project root 
- Update native build script so it only runs if the package declares `package.json#napi.targets`
- Will use this to split napi builds into separate packages
[no-changeset]: updating build script

Update build script to avoid double builds for napi projects

---

.github/workflows/release.yml

There are a bunch of version packages PRs being opened on weird branches, which it turns out is triggered by running a dev release with the manual `workflow_dispatch` step. We don't want changesets to step in here, so I'm preventing it from running unless we're on `main`
Add a simple conditional check to the job to make sure the branch is main
[no-changeset]: Updating workflow file

Only run the changesets job on main

---

packages/core/integration-tests/test/watcher.js

This test seems to be hanging the Mac V3 test suite and has gotten worse lately. This PR temporarily disables it.
[no-changeset]: Test change

Disable hanging V3 test

---

.changeset/good-fishes-reflect.md
packages/core/utils/package.json

The inline string replacement perf change didn't end up having the effect we wanted, but it turns out that's because it never got activated.
The build for utils bundles its node_modules into the final output, so feature-flags just needed to be added to the list of dependencies not to bundle.

Don't include the feature flags package in the included node_modules for utils

---

packages/core/integration-tests/test/watcher.js

Looks like have any watcher native tests enabled can cause hangs. I'm going to disable completely and fix this soon.
[no-changeset]: Test only change

Disable all native watcher integration tests

---

.changeset/rude-dragons-exercise.md
.vscode/launch.json
packages/core/core/src/public/BundleGraph.js
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js
packages/core/integration-tests/test/conditional-bundling.js
packages/core/types-internal/src/index.js
packages/examples/conditional-bundling/package.json
packages/examples/conditional-bundling/serve.js
packages/packagers/js/src/ScopeHoistingPackager.js
packages/reporters/conditional-manifest/src/ConditionalManifestReporter.js

One thing that was missed when implementing conditional bundling, was the unstable async runtime in use in Jira. If we get a race condition, async bundles may load too late.
This change adds support for conditional bundles into the async runtime, by making sure the runtime is added for additional bundles.

Support async runtime in conditional bundling

---

scripts/prepare-os-arch-package.mjs

Pipeline is not able to publish with error:
```
Cannot read properties of undefined (reading 'prepack')
```
The `prepack` and `prepublish` scripts are both run by lerna. The script originally mutated the `package.json#scripts` to remove the `prepack` and `prepublish` scripts after being run once - however that breaks the script if it's run a second times.
This PR changes the prepublish script so it doesn't remove the package.json scripts allowing it to be called multiple times.
[no-changeset]: Updating pipeline

Fix the prepublish script for bin packages (apvm)

---

.changeset/nervous-singers-tickle.md
packages/core/core/src/RequestTracker.js

On certain scenarios the cache is known to be up-to-date, such as starting-up
an instance from a snapshot which has a working cache.
On such scenarios, querying either `watchman` or vcs is also relatively
expensive, because the machine's data might still be in the process of being
initialized.
This diff adds an environment variable to skip cache invalidation completely.
Test Plan: N/A

Add env variable to skip cache invalidation

---

.changeset/nice-ghosts-applaud.md
crates/atlaspack_vcs/src/lib.rs

There are problems getting the diff with libgit on sparse checkouts.
Test plan: yarn test:integration

Use git CLI for getting the diff

---

.github/workflows/ci.yml
.github/workflows/release.yml

I noticed that most of our native compile steps are not getting a cache hit and therefore running for around 10 minutes when it's closer to [3 mins](https://github.com/atlassian-labs/atlaspack/actions/runs/14828609067/job/41625622751?pr=490) with a cache hit. I believe this is mostly due to the 10GB github action cache limit evicting our caches. 
According to the [rust-cache docs](https://github.com/Swatinem/rust-cache) 
> Caches from base branches are available to PRs, but not across unrelated branches.
Therefore I think it's more efficient to just re-use the cache generated from main on all PRs. 
Only save the rust-cache in CI from the main branch, running in restore-only mode for PRs. 
[no-changeset]: CI only change

Only store rust-cache on main branch

---

scripts/debug-symbols.mjs

In the context of the super build, debug symbols can be stripped from the `node_modules` of inner packages so this updates the debug symbols script to ignore inner `packages/**/*/node_modules`.
[no-changeset]: updating build script

Skip node_modules in debug symbols script

---

.changeset/chilled-vans-fly.md
Cargo.lock
crates/atlaspack_swc_runner/src/runner.rs
packages/transformers/js/core/Cargo.toml
packages/transformers/js/core/src/lib.rs
packages/transformers/js/core/src/node_replacer.rs

When working on the super build, I needed to disable the automatic node replacements of `__filename` and `__dirname` in multiple places. To support this I added a new special comment that can be placed before any references to those global globals which will bypass the replacement logic. The solution takse inspiration from [pure notation comments](https://github.com/javascript-compiler-hints/compiler-notations-spec/blob/main/pure-notation-spec.md). 
In future, we could also potentially use this as a way to inline disable other compiler behaviours.
Example usage
```js
const dirname = /*#__ATLASPACK_IGNORE__*/ __dirname;
```

Support atlaspack ignore comments for node replacements

---

.changeset/brown-tomatoes-argue.md
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js
packages/reporters/conditional-manifest/package.json
packages/reporters/conditional-manifest/src/ConditionalManifestReporter.js
packages/reporters/conditional-manifest/test/ConditionalManifestReporter.test.js

We get spammed logs in the console at the end of builds in jira, which is annoying and a bit confusing for devs.
When the feature flag is enabled, we hash the result and only write/log when the hash changes.

Avoid duplicated file writes to disk in ConditionalManifestReporter

---

.github/actions/setup-node/action.yml
.github/workflows/ci.yml
.github/workflows/release.yml

Currently, node caches are filling our github action allowance for not much benefit. This PR shared the node install, yarn install and yarn cache workflow into a composite action. I've also disabled the built-in setup-node yarn caching in favour of a simpler solution implemented directly in the action. 
From now on yarn caches will only be stored on the main branch, PRs only using a restore. 
[no-changeset]: On CI changes

Only store yarn cache on main branch

---

.github/workflows/release.yml

Currently when the Changesets action opens the Version Packages PR, it uses the default `GITHUB_TOKEN` provided by GitHub Actions.
However PRs opened using this token don't have [permission to kick off] CI.
[permission to kick off]: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
The [best practices solution] seems to be to make a GitHub app and then use that to authenticate and get a token that is allowed to run CI.
We've gotten the open source admins to make one for us, and now we can use the [official get-a-token action][a] to auth properly.
[best practices solution]: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#granting-addi …

Use the new GitHub app to auth changesets

---

.github/workflows/release.yml

It seems that this is an alternative to setting up the permissions in the App settings, and I'm concerned that this is overriding the ones I've set. I want to try taking them out
[no-changeset]: Update workflows

Remove the permissions line from the yaml file

---

.github/workflows/canary-release.yml
.github/workflows/ci.yml
.github/workflows/dev-release.yml
.github/workflows/release.yml
Cargo.toml
package.json
scripts/build-native.js
scripts/debug-symbols.mjs
yarn.lock

On release builds, we currently extract debug-symbols for each target and merge them into a single artifact to be handled later. This PR instead just uploads the debug-symbols straight to Sentry and then deletes them. 
- Add sentry CLI and update the `debug-symbols` script to upload to Sentry
- Removed the `canary` rust profile in favour of using the builtin `release` profile with `debug = true`
- Add `opt-level = 3` to the default `dev` profile, allowing us to viably dev against `yarn build-native` locally which harnesses incremental builds
[no-changeset]: Release pipeline change

Upload debug symbols to sentry

---

.github/workflows/release.yml
scripts/debug-symbols.mjs

- Sometimes you want to strip debug symbols without uploading to Sentry
- Sometimes you want to remove debug symbols
Added options to `debug-symbols.mjs` script
```bash
node ./scripts/debug-symbols.mjs
node ./scripts/debug-symbols.mjs --upload-to-sentry
node ./scripts/debug-symbols.mjs --rm
node ./scripts/debug-symbols.mjs --upload-to-sentry --rm
```
[no-changeset]: Build script

Chore: Add options to sentry script

---

.changeset/spotty-shrimps-sneeze.md
packages/apvm/apvm/apvm.mjs

`yarn install` resets permissions on binaries. This change checks the binary has the correct permissions before running it and if not, sets the correct permissions

Apvm: Reset bin permissions on unix

---

.changeset/fuzzy-zoos-sniff.md
crates/apvm/src/cmd/link_npm.rs
crates/apvm/src/cmd/link_release.rs

Fixing "package.json#main" specifier in npm shims produced by "apvm link"

APVM : Fix "main" in package.json

---

.changeset/heavy-apricots-study.md
packages/core/cli/src/makeDebugCommand.js

This will only make sure the cache key in use is for a no-lazy build.

Change debug build-asset-graph to do no-lazy build

---

.gitmodules
benchmarks/three-js/.gitignore
benchmarks/three-js/scripts/build.mjs

Some consumers are complaining about the three-js submodule used for benchmarks when vendoring the repo to use unpublished crates.
- Replaces the submodule with a command that fetches the branch
- Runs the atlaspack build in a subshell because reruns of the programmatic API are broken
[no-changeset]: Benchmarks aren't published

Chore: Replace the three-js submodule

---

.changeset/strong-carrots-provide.md
packages/core/core/src/RequestTracker.js
packages/dev/query/src/index.js

Eliminating large blob writes so that we can improve the time it takes to write to cache

Modify "large blobs" to be written to the LMDB cache

---

.changeset/long-pans-sit.md
crates/atlaspack_monitoring/src/lib.rs

It is not valid to set the global tracing subscriber multiple times in a process, so we should never drop our monitoring because we will fail to initialize it again.

Fix setting-up monitoring multiple times

---

.changeset/cold-moles-return.md
packages/bundlers/default/src/bundleMerge.js
packages/bundlers/default/src/bundlerConfig.js
packages/bundlers/default/src/idealGraph.js
packages/core/integration-tests/test/bundler.js

Add `sharedBundleMergeThreshold` config option
In apps with lots of dynamic imports, many shared bundles are often removed
from the output to prevent an overload in network requests according to the
`maxParallelRequests` config. In these cases, setting `sharedBundleMergeThreshold` can
merge shared bundles with a high overlap in their source bundles (bundles that share the bundle).
This config trades-off potential overfetching to reduce asset duplication.
The following config would merge shared bundles that have a 75% or higher overlap in source bundles.
```json
{
"@atlaspack/bundler-default": {
"sharedBundleMergeThreshold": 0.75
}
}
```

Add shared bundle merging feature 

---

.changeset/spotty-carrots-attend.md
packages/core/fs/src/NodeVCSAwareFS.js
packages/core/rust/index.js.flow

Previous PRs introduced timings, but didn't expose the data:
- [PR](https://github.com/atlassian-labs/atlaspack/pull/344) with timing for dirty hashes listings: `dirty_files_execution_time`
- [PR](https://github.com/atlassian-labs/atlaspack/pull/346/files) with timing for yarn state scanning: `yarn_states_execution_time`
This PR exposes the timings info so that we can report them in dev metrics.
Tested locally:

expose VCS timing metrics to analytics

---

.changeset/rare-countries-chew.md
packages/bundlers/default/src/idealGraph.js

When we were [adding shared bundle merging](https://github.com/atlassian-labs/atlaspack/pull/535), we were getting some nullthrows errors in the build but it wasn't clear where from. We added numbers to each instance of nullthrows, but forgot to take a few of them out.
[no-changeset]: Tweaks to unreleased code

Remove left over nullthrows numbers used for troubleshooting

---

.changeset/clever-dolls-type.md
crates/lmdb-js-lite/src/lib.rs
crates/lmdb-js-lite/src/writer.rs
crates/node-bindings/src/lmdb.rs
packages/core/cache/package.json
packages/core/cache/src/LMDBLiteCache.js
packages/core/cache/test/LMDBLiteCache.test.js
packages/core/cli/src/makeDebugCommand.js
packages/core/core/src/Atlaspack.js
packages/core/rust/index.js.flow

Adds a command to copy over a database compacting free pages.
This should make the database files more space efficient.
Test Plan: yarn test:unit

Add database compaction command

---

.github/workflows/release.yml

Originally I had changesets and canary release running simultaneously, since they have nothing to do with each other.
Unfortunately it seems that the NPM backend doesn't like this, and the builds fail when they try to release. Re-running the process works fine.
In the near future we'll get rid of canary and dev releases (in favour of [Changesets Snapshots](https://github.com/changesets/changesets/blob/main/docs/snapshot-releases.md)), and so this won't be a problem anymore, but for now the easiest thing is to just make them run sequentially.
[no-changeset]: Updating workflow

Make changesets run after canary

---

.changeset/loud-maps-punch.md
packages/core/core/src/RequestTracker.js
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js

Log counts of nodes invalidated for each type. Forward logs with
`trackableEvent`.
Test Plan: N/A

Add verbose logging of request invalidation

---

.changeset/young-emus-work.md
packages/core/core/src/Atlaspack.js

We need the ability to control the number of threads used by Tokio in the native context
Added an environment variable `ATLASPACK_NATIVE_THREADS` to control the number of Tokio threads

Native: Added ATLASPACK_NATIVE_THREADS

---

.changeset/wild-brooms-hide.md
crates/atlaspack_vcs/src/lib.rs
packages/core/integration-tests/test/vcs-cache.js
scripts/build-native.js

Fix bug where switching backwards in history would not properly report changes.
Fix bug where duplicate events were logged for diffed, dirty or previously
(snapshot) dirty files.

Fix a few VCS cache invalidation bugs

---

.changeset/perfect-paws-study.md
packages/core/core/src/public/BundleGraph.js
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js
packages/core/integration-tests/test/conditional-bundling.js
packages/reporters/conditional-manifest/src/ConditionalManifestReporter.js

@flakeparadigm noticed that his code was not getting preloaded in Jira. We isolated this to reusing the same condition for two different imports. 
This change fixes the conditional manifest reporter, which was erroneously overriding the previous condition bundles. It is gated behind a feature flag.

Fix conditional bundling reporter when condition is reused

---

.changeset/tame-cheetahs-suffer.md
packages/core/conditional-import-types/index.d.ts

Update doc comment for conditional imports to remove outdated information and to make the parameters clearer.
This is now outdated:
```
**IMPORTANT: This API is currently a no-op. Do not use until this message is removed.**
```
and there was one instance where it caused confusion for a developer. We should remove it.
* Remove outdated message
* Clarify the syntax for `ifTrueDependency` and `ifFalseDependency`

Fix conditional import types

---

.github/workflows/ci.yml

Remove node 18 on test suites and CI jobs.
[no-changeset] CI changes
Test Plan: CI

Do not run CI on node 18

---

.changeset/violet-steaks-thank.md
crates/lmdb-js-lite/__benchmarks__/prepare-read-benchmark.ts
crates/lmdb-js-lite/__benchmarks__/write-throughput-safe.ts
crates/lmdb-js-lite/__test__/index.test.ts
crates/lmdb-js-lite/src/lib.rs
crates/node-bindings/src/atlaspack/atlaspack.rs
crates/node-bindings/src/lmdb.rs
packages/core/cache/test/LMDBLiteCache.test.js
packages/core/cache/test/workerThreadsTest.js
packages/core/rust/index.js.flow
packages/core/test-utils/src/utils.js

Do not allow database handle to hold a closed DB reference.

Never manually close the LMDB handle

---

.changeset/clean-eyes-rush.md
packages/core/core/src/Atlaspack.js
packages/core/core/src/RequestTracker.js
packages/core/core/test/RequestTracker.test.js

Modify RequestTracker to report paths that end up triggering lots of
invalidations.
Change is flagged but the flag is turned on by default.
Test Plan: yarn test:js:unit

Report top 10 paths with largest invalidations

---

.changeset/wild-apricots-divide.md
crates/lmdb-js-lite/src/writer.rs

It is possible on certain use cases that the LMDB database will run out of
reader slots if processes are quit while keeping the database open.
This adds a call which will check and clean stale readers, fixing a database
that has become unable to be opened.
Test Plan: N/A

Fix LMDB database running out of reader slots

---

.changeset/fuzzy-fireants-sleep.md
packages/core/core/src/requests/WriteBundleRequest.js
packages/core/core/src/requests/WriteBundlesRequest.js
packages/core/core/src/types.js

When building cache analysis tools, it is useful to be able to link a write
bundles request to the bundle that it has written, since the final output path
of a bundle is not available otherwise.
This modifies the WriteBundleRequest to include the bundleId that has been
written in the request result, which will get persisted to its request node on
the cache.
Test Plan: N/A

Add bundleId to write bundles request result

---

packages/dev/query/src/index.js

Under the `cachePerformanceImprovements` feature-flag, cache keys have changed.
This commit updates @atlaspack/query helper functions to work with that branch.
[no-changeset]: Internal use only
Test Plan: N/A

Fix @atlaspack/query with cache changes

---

.changeset/smooth-suits-tan.md
packages/core/core/src/EnvironmentManager.js
packages/core/core/src/RequestTracker.js
packages/core/core/test/EnvironmentManager.test.js
packages/core/core/test/RequestTracker.test.js
packages/core/integration-tests/test/cache.js

PR, based on https://github.com/atlassian-labs/atlaspack/pull/572
---
- We want to list all environments using `getAllEnvironments` then store them into the cache inside of `RequestTracker::writeToCache`
- Environments should be stored as: `Environment/$ATLASPACK_VERSION/$ENVIRONMENT_ID`
- A separate key should be stored: `EnvironmentManager/$ATLASPACK_VERSION`. This should contain the list of environment IDs used in the last build.
- When loading the request tracker in `loadRequestGraph`, we should load the environments required for the previous build.

Write and load deduplicated environments from cache

---

.changeset/perfect-pianos-judge.md
.changeset/quiet-files-jump.md
packages/bundlers/default/package.json
packages/bundlers/default/src/bundleMerge.js
packages/bundlers/default/src/bundlerConfig.js
packages/bundlers/default/src/idealGraph.js
packages/bundlers/default/src/memoize.js
packages/core/graph/src/BitSet.js
packages/core/graph/test/BitSet.test.js
packages/core/integration-tests/test/bundler.js
packages/core/test-utils/src/utils.js
yarn.lock

Building on the work in #535, this PR adds a more options and configurability to shared bundle merging. We're introducing a new `sharedBundleMerge` option to the bundle config that allows you to pass multiple merge groups with different configurations. The groups are ordered by priority so any bundles merged by a former category are not-available for merging in a lower priority one. 
This new config replaces the previously released `sharedBundleMergeThreshold`. 
The following options are available for each merge group.
> The same as `sharedBundleMergeThreshold` from #535
Merge bundles share a percentage of source bundles
```json
"@atlaspack/bundler-default": {
"sharedBundleMerge": [{
"overlapThreshold": 0.75
}]
}
```
Merge bundles that are smaller than a configured amount of bytes. 
> …

Merge common shared bundles

---

.changeset/dirty-nails-double.md
packages/bundlers/default/src/idealGraph.js
packages/core/integration-tests/test/bundler.js

When enabling inline constants for one of our internal products, we had errors where "constant modules" weren't being included in MSBs if they didn't match the MSB regex which would cause an error during packaging.
A bug was fixed in `makeManualAssetToConfigLookup` to ensure constant modules were added to the mapping _before_ the regex check and early bailout.

Fix constant modules not being included in MSBs

---

packages/core/graph/benchmark/BitSet.js
packages/core/graph/package.json
yarn.lock

As we were adding the `size` method to BitSet, we were considering a few different algorithms, and wanted to test them for performance. The BitSet class is used specifically when performance is sensitive, so making sure the new method was performant is an essential part of weighing options.
This led to setting up a `benny` benchmark in the repo, which is probably handy to just have, so committing it to the repo for future reference and as a placeholder for other changes people may want to make.
It runs by just calling the script with node, which can be done with the `benchmark` script in that package.
```
yarn workspace @atlaspack/graph benchmark
```
[no-changeset]: Benchmark testing

Add a benchmarks file for BitSet

---

.changeset/large-moons-sleep.md
crates/apvm/src/cmd/link_local.rs

The `ATLASPACK_DEV` branch of the `.bin/atlaspack` script didn't work because `@atlaspack/babel-register` is a private package, so the `reqiure('@atlaspack/register')` would fail.
Change the `require` call to instead directly reference the path, using `APVM_ATLASPACK_LOCAL`. Seems to work!

Use direct reference to private babel-register package in APVM Atlaspack script

---

.changeset/yellow-fans-argue.md
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js
packages/core/integration-tests/test/conditional-bundling.js
packages/packagers/html/package.json
packages/packagers/html/src/HTMLPackager.js

The current behaviour for the `evaluateRootConditionalBundles` config item is not sufficient for all gates in Jira. We need to load the same bundles as in the manifest.
This change refactors to use `getConditionalBundleMapping` as the source of truth for loading the HTML, when we're in environments that don't evaluate the condition in the webserver.

Load more conditional bundles in HTML when root bundles config enabled

---

package.json

I keep checking-in files with eslint errors.
This changes the pre-commit hooks to run eslint
[no-changeset]: Not applicable
Test Plan: N/A

Run eslint on pre-commit hook

---

.changeset/spicy-shoes-hear.md
.changeset/twenty-pumas-jump.md
packages/bundlers/default/src/bundleMerge.js
packages/core/utils/benchmark.js
packages/core/utils/package.json
packages/core/utils/src/collection.js
packages/core/utils/src/index.js

It turns out that in the specific use case we have in finding merge candidates, creating and intersecting a BitSet is actually slower than just using the existing Sets.
The collections util only had an intersect method that mutates the first Set passed in, so I've added another one that leaves the Sets unchanged.
This speeds up the `findMergeCandidates` function by about 35%.
I've also committed the benchmarking setup I was using, for future experimenting.

Remove bitsets from bundle merging

---

.changeset/small-fireants-approve.md
.changeset/small-students-march.md
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js
packages/core/integration-tests/test/scope-hoisting.js
packages/packagers/js/src/ScopeHoistingPackager.js

We did some testing of the scope hoisting packager, and it turns out that for one of our products, only 0.6% of assets are actually hoisted, with the rest being wrapped in `parcelRegister`.
This is because anything that's dynamically imported needs to be wrapped, and all children of wrapped assets also get wrapped. It seems like the original intention for this was to handle the case of a circular dependency, but it's a pretty big blast radius.
This change adds a new feature flag `applyScopeHoistingImprovement` which allows children of wrapped assets to be inlined into the wrapped asset. This is achieved by assigning assets to their wrapped parents and if multiple parents are detected then they becomes wrapped themselves. 
We've also had to exclude assets that contain symbols that are …

Add scope hoisting of assets inside wrapped assets

---

.changeset/spicy-cups-invite.md
packages/core/core/src/index.js
packages/core/integration-tests/test/api.js
packages/core/integration-tests/test/cache.js
packages/core/integration-tests/test/conditional-bundling.js
packages/core/integration-tests/test/vcs-cache.js

Make the tests more robust - needed for the TypeScript migration
Remove `import "@atlaspack/*/src/**"` from integration test imports by publically exporting the value at the destination

Remove import "@atlaspack/*/src/**" from integration test imports 

---

.changeset/fast-dots-impress.md
packages/core/core/package.json
packages/core/logger/package.json
packages/core/workers/package.json

Removing `package.json#exports` from the Atlaspack packages to avoid confusion between Nodejs's built-in conditional exports and our custom babel-register JIT `package.json#source`/`package.json#main` rewrite.
The migration to TypeScript will use Nodejs conditional exports for TypeScript packages and the babel-register hack for Flow packages.
Eventually the babel-register hack will be removed and switching between `src`/`lib` will be done with built-in Nodejs conditional exports 
- Remove `package.json#exports`

Remove package.json#exports (temporarily) 

---

.changeset/stale-gorillas-teach.md
packages/core/core/src/AssetGraph.js
packages/core/core/src/Environment.js
packages/core/core/src/EnvironmentManager.js
packages/core/core/src/public/MutableBundleGraph.js
packages/core/core/src/requests/AssetGraphRequestRust.js

* Fix a missing ref conversion where the ref would be kept as an object even
with the flag enabled
* Fix rust compatibility with the environment deduplication flag
A subsequent change will modify rust asset graph so it doesn't copy
environments over. We expect a non-negligible performance improvement to native
builds from that change.
Test Plan: N/A

Fix bug with environment ID being ref

---

packages/core/integration-tests/package.json

Can't run `yarn add -D <anything>` in `packages/core/integration-tests` because it complains that:
```
error An unexpected error occurred: "expected workspace package to exist for \"rimraf\"".
```
Seems the dependency is missing from the `package.json`, adding it in resolves the issue.
[no-changeset]: Integration tests devdeps only

Add rimraf to integration-test devDeps

---

.changeset/clean-humans-fetch.md
.changeset/rich-hairs-poke.md
.changeset/slimy-dingos-approve.md
packages/core/utils/src/debug-tools.js
packages/core/utils/src/index.js
packages/packagers/js/package.json
packages/packagers/js/src/ScopeHoistingPackager.js
packages/reporters/cli/src/CLIReporter.js
yarn.lock

When I'm trying to identify issues with Atlaspack builds, there are a couple of things I always change to my local version to make things a bit easier.
Probably makes sense to move them out of my permanent stash and into the repo for everyone to enjoy.
This PR introduces the concept of "debug tools", and implements the first two. It's intended that we can add others in future as ideas come up.
Debug tools are enabled via an env var (which I'm setting permanently in my shell config), with instructions added to the `debug-tools.js` file.
The two tools that are implemented here are:
When doing a build in our internal applications, several thousand bundles are created, and listing the file path of every single one takes up an annoying amount of space in the terminal and is not useful to me at …

Add a handful of debugging tools

---

.changeset/fair-insects-sell.md
.mocharc.js
docs/debugging-tests.md
packages/core/core/test/RequestTracker.test.js
packages/core/core/test/requests/ConfigRequest.test.js
packages/core/e2e-tests/.mocharc.json
packages/core/e2e-tests/test/e2e-tests.test.js
packages/core/integration-tests/.mocharc.js
packages/core/integration-tests/test/react-refresh.js
packages/core/test-utils/package.json
packages/core/test-utils/src/mochaSetup.js
packages/core/test-utils/src/utils.js
packages/core/workers/test/workerfarm.test.cjs
yarn.lock

We've had Mocha doing a force `exit` at the end of tests when they "hang". This potentially masks issues where resources (such as worker pools) are not properly cleaned up. I was able to reproduce a "hang" when using Atlaspack V3 via the `Atlaspack` JS API that wasn't reproducible in a test because of this.
The reason for having that `exit: true` dates back to an issue from 2019 or earlier which is long resolved.
* Removed the "exit: true" from all the Mocha configs, and restored the `after()` hook to dispose of shared test worker pools in test-utils.
* Added a `ATLASPACK_MOCHA_HANG_DEBUG` env var for tests that can help to debug hangs by setting up https://github.com/mafintosh/why-is-node-running and allowing you to dump out what handles are still open
* Fixed several unit and …

Remove exit:true for Mocha tests

---

.github/workflows/ci.yml

The Mac integration test suite is consistently timing out atm. This PR increases the timeout from 35 mins to 45 mins to hopefully get more green builds. 
[no-changeset]: CI only change

Increase the integration timeout to 45 mins

---

.changeset/late-phones-joke.md
packages/core/core/src/Atlaspack.js
packages/core/integration-tests/test/cache.js
packages/core/integration-tests/test/tracing.js
patches/mocha+8.4.0.patch

Integration tests are slow, and seem to slow down over time. It was identified that the tracing test would cause the tracer to be enabled. As the tracer is a module level object, it meant that even if tracing was enabled on subsequent uses of `Atlaspack`, the tracer would remain enabled.
Add a disposable to disable the tracer when Atlaspack is torn down if it has been enabled.

Ensure tracer is disabled at the end of the build

---

.changeset/beige-balloons-add.md

The `@atlaspack/rust` package should have been bumped in #633. This has resulted in the JS half of those changes being released, but not the Rust half.
Rectifying by creating a new changeset now.

bump @atlaspack/rust

---

.changeset/wise-peas-visit.md
packages/core/core/src/Atlaspack.js

If the `atlaspackV3CleanShutdown` feature flag is enabled but `atlaspackv3` isn't then an error will occur when Atlaspack exits as the disposable is added even if `rustAtlaspack` isn't defined.
Move the addition of the disposable inside the "if Atlaspack v3" check.

Move adding of APV3 disposable to correct place

---

.changeset/gorgeous-teachers-reflect.md
crates/atlaspack_plugin_transformer_js/src/js_transformer/conversion.rs
packages/core/core/src/SymbolPropagation.js
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js
packages/core/integration-tests/test/integration/scope-hoisting/es6/empty-module/a.js
packages/core/integration-tests/test/javascript.js
packages/core/integration-tests/test/scope-hoisting.js
packages/transformers/js/core/src/lib.rs
packages/transformers/js/src/JSTransformer.js

This PR fixes an issue where star re-exports of empty files (usually occurring in compiled typescript libraries) could cause exports to be undefined at runtime. This can occur as empty files are treated as CJS which potentially can have their exports mutated from outside sources and therefore get marked as potentially containing the superset of the exports for the library. 
In the past we have worked around this by [only performing this behaviour for Assets that are marked as having side effects](https://github.com/parcel-bundler/parcel/pull/9079). However in NPM packages (older versions of `@apollo/client` for example) this value is out of our control. 
The solution we've gone with here is to remove the `*` wildcard export from these empty files, when all incoming deps are ESM type, …

Fix star re-export of empty files causing runtime errors

---

packages/core/core/src/PackagerRunner.js
packages/core/core/src/requests/WriteBundlesRequest.js
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js
packages/core/types-internal/src/index.js
packages/core/utils/src/index.js
packages/core/utils/src/progress-message.js
packages/reporters/cli/src/CLIReporter.js

This PR adds a new progress update experience during packaging via the default CLI reporter. I would like to evolve this experience a bit more overtime however this is a small improvement we can ship reasonably easily. The new experience is enabled by the `cliProgressReportingImprovements` flag. 
The new experience is designed to give a lightweight indication of how the build is progressing, in both CI and locally, showing the total number of bundles in the build, the amount of bundles completed packaging so far and the rounded percent complete. 
In environments that don't support live updating of the output, we push a progress update everytime a threshold is reached. Currently the thresholds are just some ballpark arbitrary values and we can update them whenever. 
| Bundles | Threshold | …

Add new packaging progress CLI experience

---

.github/workflows/ci.yml
.mocharc.js
scripts/check-rust-changes.js
scripts/check-rust-changes.test.js
scripts/test/check-rust-changes.test.js

Add CI job to check for rust files in PRs and notify devs if they have not include the rust package in their changeset via a PR comment.
As a follow up from debugging an apparent issue with feature flag evaluation, we discovered that the developer did not include @atlaspack/rust in their changeset, so their updated code never got published to npm.
The current yarn changeset command checks for packages that are updated, but file changes to .rs files do not directly change the code in the @atlaspack/rust package, so the developer is not prompted to add @atlaspack/rust to the changeset.
Introducing `ferris-atlaspack-bot`! Ferris will helpfully add a PR comment to notify developers to consider adding the `@atlaspack/rust` package to their changeset if they want to have their Rust changes get …

Add GitHub action to check for modified rust files in PRs and notify devs if they have not include the rust package in their changeset

---

.changeset/shy-impalas-sip.md
packages/core/cache/src/LMDBLiteCache.js

Fix issues related to new large blob behaviour not being atomic.
For example, concurrent `setLargeBlob` and `getLargeBlob` might return contents before they are fully written on `main`.

Fix bug related to partial non-atomic cache writes

---

.changeset/small-cooks-chew.md
packages/core/core/src/AssetGraph.js
packages/core/core/src/requests/AssetGraphRequest.js
packages/core/core/src/requests/BundleGraphRequest.js
packages/core/core/test/AssetGraph.test.js
packages/core/core/test/RequestTracker.test.js
packages/core/feature-flags/src/index.js
packages/core/feature-flags/src/types.js

A common bug seems to be that the dev-server eventually hits exceptions:
```
"Expected content key ... to exist"
```
When this happens, the cache must be cleared, otherwise the dev-server is
unable to build.
Similar to https://github.com/atlassian-labs/atlaspack/pull/652, the reason this might happen is due to state corruption.
This PR adds a test which reproduces the exception by executing the following
sequence of events:
- Perform a build
- Perform a build which is not safe to incrementally bundle (such as adding a
new dependency)
- "Abort" the build before bundling completes
- Perform a new build, which has changes to assets that haven't been seen by
the bundler
This causes the asset graph to be marked as "safe to incrementally bundle",
despite the bundle graph being out-of-sync with …

Fix content key not found exceptions

---

packages/dev/esm-fuzzer/package.json
packages/examples/conditional-bundling/package.json
packages/examples/eslint/package.json
packages/examples/kitchen-sink/package.json
packages/examples/react-hmr/package.json
packages/examples/react-refresh/package.json
packages/examples/simple/package.json
packages/examples/typechecking/package.json
packages/examples/typescript/package.json
packages/optimizers/inline-requires/package.json
scripts/validate-workspace-versions.mjs

Sometimes a rebase or merge can cause drift between workspace `dependencies` and `devDependencies` causing yarn to install dependencies from npm rather than using their local versions.
This script scans the workspace packages to make sure the versions match the ones in the workspace
[no-changeset]: Dev Script

DevScript: Workspace versions validator

---

packages/core/integration-tests/test/cache.ts
packages/core/test-utils/package.json
packages/core/test-utils/src/utils.ts
packages/dev/mocha-profiler/package.json
yarn.lock

macOS integration tests seem to be getting slower again. [Profiling](https://github.com/atlassian-labs/atlaspack/pull/603) revealed two large hot spots both originating from the Cache tests:
* https://github.com/atlassian-labs/atlaspack/blob/main/packages/core/test-utils/src/utils.ts#L1327-L1381
* writing snapshots in the watcher
This PR changes the watcher backend to `fs-events` on macOS. This reduces the CI time by approx 4-5 min (from ~30min to ~26min) based on two test runs.
~~I did also try and optimise the `assertNoFilePathInCache` but the few things I tried weren't any faster (using a chunked faster string search algo, scanning in a promise queue, using a Rust based function for searching for the string in the file).~~
`assertNoFilePathInCache` was optimised to use a promise queue …

Improve macOS integration test performance

---

.changeset/silent-pandas-beam.md
packages/core/core/src/Atlaspack.ts
packages/core/feature-flags/src/index.ts
packages/core/integration-tests/test/atlaspack-v3.ts

Change is fully rolled out now, can be cleaned up.
Cleaned up the `atlaspackV3CleanShutdown` feature flag.

Cleanup atlaspackV3CleanShutdown feature flag

---

.changeset/short-needles-dream.md
crates/atlaspack_core/src/types/asset.rs
crates/atlaspack_core/src/types/bundle.rs
crates/atlaspack_plugin_transformer_html/src/html_dependencies_visitor.rs
crates/atlaspack_plugin_transformer_html/src/html_transformer.rs
crates/node-bindings/src/atlaspack/dependency.rs
packages/bundlers/default/src/MonolithicBundler.ts
packages/bundlers/default/src/bundleMerge.ts
packages/bundlers/default/src/idealGraph.ts
packages/core/core/src/Atlaspack.ts
packages/core/core/src/BundleGraph.ts
packages/core/core/src/PackagerRunner.ts
packages/core/core/src/atlaspack-v3/worker/compat/bitflags.ts
packages/core/core/src/requests/WriteBundlesRequest.ts
packages/core/core/src/types.ts
packages/core/feature-flags/src/index.ts
packages/core/integration-tests/test/html.ts
packages/core/types-internal/src/index.ts
packages/core/utils/src/replaceBundleReferences.ts
packages/packagers/js/src/DevPackager.ts
packages/packagers/js/src/ScopeHoistingPackager.ts
packages/runtimes/js/src/JSRuntime.ts
packages/transformers/html/package.json
packages/transformers/html/src/inline.ts
packages/transformers/html/test/HTMLTransformer.test.ts

In some use cases we want to bundle multiple HTML entries with inline scripts that depend on shared code, however we don't want Atlaspack to produce a shared bundle - we want to keep all the bundled code within the inline script.
Essentially we want the inline script to also be isolated, something that is not previously supported by Atlaspack.
Implement a new attribute to tell Atlaspack that an inline script should be isolated: `<script data-atlaspack-isolated>`. With this attribute, the script will use a new bundle behaviour called `inlineIsolated` which is a combination of both inline and isolated.
The majority of the change is adding conditions for this new `bundleBehavior` everywhere there's a check for `inline` or `isolated` to ensure the new `bundleBehavior` is both.
There is a new …

Add support for isolating inline scripts

---

.changeset/chilly-carrots-check.md
.changeset/soft-walls-provide.md
crates/apvm/src/cmd/atlaspack.rs
crates/apvm/src/cmd/install.rs
crates/apvm/src/cmd/install_npm.rs
crates/apvm/src/cmd/link.rs
crates/apvm/src/cmd/link_npm.rs
crates/apvm/src/cmd/uninstall.rs
crates/apvm/src/context.rs
crates/apvm/src/main.rs
crates/apvm/src/platform/bin_path.rs
crates/apvm/src/platform/constants.rs
crates/apvm/src/platform/runtime.rs
packages/core/atlaspack/static/build-cache/index.d.ts
packages/core/atlaspack/static/bundler/default/index.d.ts
packages/core/atlaspack/static/bundler/library/index.d.ts
packages/core/atlaspack/static/codeframe/index.d.ts
packages/core/atlaspack/static/events/index.d.ts
packages/core/atlaspack/static/graph/index.d.ts
packages/core/atlaspack/static/logger/index.d.ts
packages/core/atlaspack/static/markdown-ansi/index.d.ts
packages/core/atlaspack/static/node-resolver-core/index.d.ts
packages/core/atlaspack/static/utils/index.d.ts
packages/core/conditional-import-types/index.d.ts

Enable APVM support with the existing unified `atlaspack` npm package: https://www.npmjs.com/package/atlaspack
- APVM changes
- Download/extract the `atlaspack` npm package
- Link the `atlaspack` package
- Support for resolving npm tags (like `latest` `dev`) 
- Added type re-exports to core packages in the `atlaspack` npm package 
The `atlaspack` package distributes Atlaspack completely unmodified so there are no consumer side changes required.
APVM will download and do a `yarn install` on the `atlaspack` package. This works fine but is a bit slow (~45s). 
This can be skipped with: 
```
apvm install --skip-postinstall latest
```
If the consumer already has a version of Atlaspack installed and you want to reuse their `node_modules`, use the `--exclude-node-modules` option:
```
apvm link …
```

APVM support via unified package

---

.changeset/shiny-pandas-develop.md
package.json
packages/core/feature-flags/src/index.ts

Use `ATLASPACK_BUILD_ENV` instead of `NODE_ENV` to determine if Atlaspack is being run in the context of Atlaspack tests.
We currently use the `ATLASPACK_BUILD_ENV` environment variable to describe the build environment context (production, development, test).
Documented here:
https://github.com/atlassian-labs/atlaspack/blob/main/docs/cli/environment-variables.md#atlaspack_build_env
When Atlaspack is running tests, we want new flags to default to true. This way, we can ensure rolling out new flags is not incompatible with existing functionality.
Note: Also added `ATLASPACK_BUILD_ENV=test` to the `test:js:unit` script.

Atlaspack flags - use ATLASPACK_BUILD_ENV instead of NODE_ENV

---

.changeset/four-frogs-mix.md
packages/runtimes/service-worker/package.json
packages/runtimes/service-worker/src/ServiceWorkerRuntime.ts
packages/runtimes/webextension/package.json
packages/runtimes/webextension/src/WebExtensionRuntime.ts
packages/transformers/typescript-tsc/src/TSCTransformer.ts
packages/transformers/webextension/src/WebExtensionTransformer.ts
packages/transformers/webmanifest/src/WebManifestTransformer.ts
packages/transformers/yaml/package.json
packages/transformers/yaml/src/YAMLTransformer.ts
packages/utils/atlaspack-watcher-watchman-js/package.json
packages/utils/atlaspack-watcher-watchman-js/src/wrapper.ts
yarn.lock

Fixes a few low hanging `@ts-expect-errors` (identified by a quick script to show packages ordered by how many ts-expect-errors, and starting from the bottom).
Removed `@ts-expect-error` annotation, fixed `@ts-expect-error`.

Fix low hanging ts expect errors 1/n

---

.changeset/cyan-radios-jog.md
packages/bundlers/default/package.json
packages/bundlers/default/src/bundlerConfig.ts
packages/bundlers/default/src/idealGraph.ts
packages/bundlers/default/src/stats.ts
packages/core/feature-flags/src/index.ts
packages/core/integration-tests/test/bundler.ts
packages/core/utils/src/debug-tools.ts
yarn.lock

This PR introduces 3 related things:
- Configurable async bundle merging for reducing total network requests
- Removal of redundant shared bundles when merging async bundles together 
- A new debug tool for outputting a report from the bundler results 
This PR adds a new bundler feature that attempts to reduce the amount of small async bundles in the output by merging them together. This is achieved by scoring all the candidates for how well they match and merging the best candidates until they meet the max overfetch size or no more good candidates are available. 
To enable the feature you can provide a new bundle config `asyncBundleMerge` with the following settings.
```
"@atlaspack/bundler-default": {
"asyncBundleMerge": {
"bundleSize": 5000,
"maxOverfetchSize": 50000,
"ignore": …
```

Add configurable async bundle merging

---

.changeset/popular-donuts-smell.md
packages/bundlers/default/src/MonolithicBundler.ts
packages/core/feature-flags/src/index.ts
packages/core/integration-tests/test/monolithic-bundler.ts

The default bundler will ensure any entry bundles have a stable name (i.e. with no hash in it). The "monolithic bundler" used when the `__unstable_singleFileOutput` option is enabled currently doesn't do this, so entry JS bundles will have a hash in their name.. the environment these bundles are used in does not expect this hash.
Added a new feature flag `singleFileOutputStableName`, when enabled will set the `needsStableName` to true when creating the entry bundles.

Use stable names for single file output bundles

---

.changeset/sixty-bananas-poke.md
packages/core/package-manager/src/NodePackageManager.ts

Ever since moving to TypeScript, Atlaspack link has not worked against source files directly. This PR re-enables that workflow when `ATLASPACK_REGISTER_USE_SRC=true` is set while still allowing external TS plugins to be compiled at runtime if needed.

Fix Atlaspack link when using against source files

---

.changeset/lucky-toys-appear.md
packages/reporters/cli/src/CLIReporter.ts

We previously added a feature flag (#691) that enabled a new experience for the packaging output that shows packaging progress rather than the name of the current bundle.
This worked great in TTY outputs, but less so with the dynamic one, where the percentage updates would show, but would then also be overwritten by the existing bundle name messaging.
If the feature flag is on, and it's a packaging or optimising event, we now just bail out of the loop early, and let the `packagingAndOptimising` events handle everything.

Fix cliProgressReportingImprovements output

---

.changeset/eight-singers-give.md
packages/packagers/js/src/ESMOutputFormat.ts
packages/packagers/js/src/ScopeHoistingPackager.ts

Most of the Maps and Sets that we have in the codebase are keyed on object references rather than id strings, but for some reason there are a bunch in the scope hoisting packager.
In theory this should be more efficient, as a reference takes up less space than a string, but this is really just about consistency.
The `assetOutputs`, `seenAssets`, and `wrappedAssets` Map/Sets have been migrated to use an `Asset` as their key.
I was also able to remove a ts-expect-error by typing the queue.

Key lookups by Asset reference instead of id string in ScopeHoistingPackager

---

.changeset/eleven-avocados-end.md
packages/packagers/js/src/ScopeHoistingPackager.ts

This PR resolves an issue where the new partial scope hoisting (`applyScopeHoistingImprovement` and `applyScopeHoistingImprovementV2`) could introduce nested `parcelRegister` calls within a `parcelRegister` which is invalid. This can happen when a skipped asset (an asset where only it's dependencies are added to the bundle) has wrapped dependencies. This is very niche and most builds likely will not run into it.
The fix here is add `parcelRequire` calls to the wrapped assets instead of attempting to inline them.
I was unable to replicate this in a test as I'm not sure how best to recreate all the edge cases in a single test and would like to  fast track the fix. I have validated it against the internal reproduction.

Fix incorrect output with skipped assets with scope hoisting improvements

---

.changeset/fluffy-rocks-buy.md
packages/core/utils/src/debug-tools.ts

Throwing is a bit aggressive here, it doesn't need to tank the build.
If an unknown debug tool is encountered then it will just log a warning instead now.

Just log a warning rather than throwing if an unknown debug tool is passed in

---

.changeset/pretty-melons-jump.md
.github/workflows/release.yml
packages/packagers/js/src/ScopeHoistingPackager.ts
packages/packagers/js/src/index.ts

This change introduces a performance optimisation for the scope hoisting packager by allowing developers to manually specify static export bindings. This can help improve runtime performance in scenarios where the automatic analysis of export bindings is not implemented (CJS).
- Added `unstable_manualStaticBindingExports` configuration option to the JS packager
- Updated the configuration schema to accept an array of strings for manual static binding exports
- Modified `ScopeHoistingPackager` to utilise the manual static binding configuration
- Improved TypeScript types and removed some type errors in the configuration loading
- Added changeset for the new feature
The new configuration option:
- Is experimental (prefixed with `unstable_`)
- Accepts an array of export names that should be …

Manual static binding exports

---

packages/bundlers/bundler-experimental/tsconfig.json
scripts/package.json
scripts/update-ts-references.mjs
tsconfig.paths.json
yarn.lock

There's a few gotchas when creating a new package in terms of making sure the tsconfig has all the right bits to ensure it builds properly and finds errors properly.
* added linting for common issues - missing composite option, missing package.json if used in src, incorrect base reference
* added fixing when not running in `--frozen` mode
[no-changeset]: tools

Add linting to ts refs script

---

.changeset/ninety-frogs-live.md
packages/core/core/src/requests/TargetRequest.ts
packages/core/core/test/TargetRequest.test.ts
packages/core/core/test/fixtures/custom-targets/package.json

While investigating avenues for configuring WIP native transformers I noticed that custom environment properties were not being used by the bundler and found that the second place assignment could be done seems to have just been overlooked.
* Add missing `customEnv` assignment from descriptor in `resolvePackageTargets`
* Add to existing tests to verify addition

Fix custom environment properties sometimes being ignored

---

.changeset/seven-pens-beg.md
packages/core/feature-flags/src/index.ts
packages/core/integration-tests/test/targets.ts

The `customEnvInTargets` feature flag is unused / rolled out so can be cleaned up.
Clean up the `customEnvInTargets` feature flag

Cleanup customEnvInTargets feature flag

---

.github/workflows/ci.yml
package.json
scripts/find-unused-feature-flags.js
scripts/package.json
yarn.lock

I accidentally released a change that had a feature flag in the feature flags list, but that feature flag wasn't actually used anywhere in the code.
We should have a lint for this, this will also help to ensure we cleanup feature flags properly.
Added a script that validates every feature flag is "used" (i.e. accessed via options or `getFeatureFlag`) somewhere in the Rust or TS code.
Added a new CI check that runs this lint and fails if there are unused flags.
[no-changeset]: scripts only

Add script to validate all feature flags are used

---

scripts/dist-differ.ts

As we make changes to the native side, there are often changes or refactors to make that should not change the output at all.
This script provides a way to validate that two builds are completely identical.
There's a new `dist-differ.ts` script in the scripts directory. It can be run with node's strip types flag, pointing to the instance of the file in your local clone of Atlaspack, and needs to be passed the two directories that you want to compare.
```
node --experimental-strip-types ~/dev/atlaspack/scripts/dist-differ.ts dist-control dist-changes
```
[no-changeset]: Local script only, no release required

Add dist differ script
